import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { CommandInput, StudioClient } from "@omp-studio/client-contract";
import { mediaInputArtifacts, validateMediaRequest, type ArtifactRecord, type MediaDetail, type MediaJob, type MediaKind, type MediaModelChoice, type MediaRequest, type MediaResultMap } from "@omp-studio/studio-protocol";
import { useI18n } from "../i18n";
import { usePreviewMode } from "../preview/PreviewContext";
import { hostErrorMessage, waitReceipt } from "../hostError";
import { PREVIEW_MEDIA_DETAIL, PREVIEW_MEDIA_INPUTS, PREVIEW_MEDIA_MODELS } from "../preview/mediaWorkbenchPreview";
import { AudioCapturePane } from "./AudioCapturePane";
import { artifactUrl } from "./ArtifactLibraryPane";
import "./mediaWorkbench.css";

export const MEDIA_INTENT_KEY = "omp.mediaIntent";
export function setMediaIntent(type: MediaKind): void { try { sessionStorage.setItem(MEDIA_INTENT_KEY, type); } catch {} }
const active = (job: MediaJob) => ["queued", "running", "waiting"].includes(job.state);
function initialKind(): MediaKind { try { const value = sessionStorage.getItem(MEDIA_INTENT_KEY); sessionStorage.removeItem(MEDIA_INTENT_KEY); if (["image", "video", "speech", "transcription"].includes(value ?? "")) return value as MediaKind; } catch {} return "image"; }
export function MediaWorkbench({ client, workspaceId, sessionId, available, onInsert, onArtifactsChanged }: { client: StudioClient; workspaceId?: string | undefined; sessionId?: string | undefined; available: boolean; onInsert?: ((text: string) => void) | undefined; onArtifactsChanged(): void }) {
  const { preview } = usePreviewMode(); const { resolvedLanguage } = useI18n(); const zh = resolvedLanguage === "zh";
  const t = (cn: string, en: string) => zh ? cn : en;
  const labels: Record<MediaKind, string> = zh ? { image: "生成图片", video: "生成视频", transcription: "转写音频", speech: "文本转语音" } : { image: "Image generation", video: "Video generation", transcription: "Transcription", speech: "Text to speech" };
  const [type, setType] = useState<MediaKind>(initialKind); const [models, setModels] = useState<MediaModelChoice[]>([]); const [model, setModel] = useState("");
  const [inputCursor, setInputCursor] = useState<string>();
  const demos = useRef(new Map([[PREVIEW_MEDIA_DETAIL.job.id, PREVIEW_MEDIA_DETAIL]]));
  const [inputs, setInputs] = useState<ArtifactRecord[]>([]); const [jobs, setJobs] = useState<MediaJob[]>([]); const [selected, setSelected] = useState<string>(); const [detail, setDetail] = useState<MediaDetail>();
  const [prompt, setPrompt] = useState(""); const [text, setText] = useState(""); const [picked, setPicked] = useState<string[]>([]); const [audio, setAudio] = useState(""); const [first, setFirst] = useState(""); const [last, setLast] = useState("");
  const [aspect, setAspect] = useState(""); const [size, setSize] = useState(""); const [count, setCount] = useState(1); const [duration, setDuration] = useState(""); const [resolution, setResolution] = useState(""); const [withAudio, setWithAudio] = useState(""); const [seed, setSeed] = useState(""); const [creativity, setCreativity] = useState(""); const [upscale, setUpscale] = useState(""); const [options, setOptions] = useState("{}");
  const [voice, setVoice] = useState(""); const [format, setFormat] = useState("wav"); const [speed, setSpeed] = useState(""); const [sampleRate, setSampleRate] = useState(""); const [bitRate, setBitRate] = useState(""); const [instructions, setInstructions] = useState(""); const [language, setLanguage] = useState(""); const [timestamps, setTimestamps] = useState("none"); const [temperature, setTemperature] = useState("");
  const [review, setReview] = useState<MediaRequest>(); const [closeId, setCloseId] = useState<string>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [fileChannel, setFileChannel] = useState(false); const [refresh, setRefresh] = useState(0);
  const epoch = useRef(0); const lock = useRef(false); const confirm = useRef<HTMLButtonElement>(null);
  const invoke = useCallback(async <K extends keyof MediaResultMap>(kind: K, input: CommandInput<K>): Promise<MediaResultMap[K]> => { const handle = await client.command(kind, input); return (await waitReceipt<{ result: MediaResultMap[K] }>(client, handle.requestId, 180000)).result; }, [client]);
  const loadInputs = useCallback(async (cursor?: string) => {
    const generation = epoch.current; if (preview) { setInputs(PREVIEW_MEDIA_INPUTS); setInputCursor(undefined); return; }
    const page = await client.query("artifacts.list", { ...(workspaceId ? { workspaceId } : {}), limit: 200, ...(cursor ? { cursor } : {}) });
    if (generation === epoch.current) { setInputs(rows => [...(cursor ? rows : []), ...page.artifacts.filter(row => ["image", "audio", "video"].includes(row.kind))] as ArtifactRecord[]); setInputCursor(page.nextCursor); }
  }, [client, workspaceId, preview]);
  useEffect(() => {
    epoch.current++; demos.current = new Map([[PREVIEW_MEDIA_DETAIL.job.id, PREVIEW_MEDIA_DETAIL]]); setInputs([]); setInputCursor(undefined); lock.current = false; setBusy(false); setError(""); setModels([]); setJobs(preview ? [PREVIEW_MEDIA_DETAIL.job] : []); setSelected(preview ? PREVIEW_MEDIA_DETAIL.job.id : undefined); setDetail(preview ? PREVIEW_MEDIA_DETAIL : undefined); setFileChannel(preview); setReview(undefined); setCloseId(undefined); setPicked([]); setAudio(""); setFirst(""); setLast(""); setModel("");
    const generation = epoch.current;
    void loadInputs().catch(cause => { if (epoch.current === generation) setError(hostErrorMessage(cause, "Media inputs unavailable")); });
    if (preview) { setModels(PREVIEW_MEDIA_MODELS); return () => { epoch.current++; }; }
    if (!available || !sessionId) return () => { epoch.current++; };
    void (async () => { const rows: MediaModelChoice[] = []; let cursor: string | undefined; const seen = new Set<string>(); do { const value = await invoke("media.models", { sessionId, ...(cursor ? { cursor } : {}) }); if (generation !== epoch.current) return; setFileChannel(value.available); rows.push(...value.models); cursor = value.nextCursor; if (cursor && (seen.has(cursor) || seen.size >= 99)) throw new Error("Media catalog exceeds its page limit"); if (cursor) seen.add(cursor); } while (cursor); setModels(rows); })().catch(cause => { if (generation === epoch.current) setError(hostErrorMessage(cause, "Media catalog unavailable")); });
    return () => { epoch.current++; };
  }, [available, sessionId, preview, invoke, loadInputs]);
  useEffect(() => { if (review) confirm.current?.focus(); }, [review]);
  useEffect(() => {
    if (preview || !available || !sessionId) return;
    let alive = true; let timer: ReturnType<typeof setTimeout>;
    const poll = async () => {
      try { if (!document.hidden) { const value = await invoke("media.list", { sessionId }); if (alive) { setJobs(value.jobs); setFileChannel(value.available); } } }
      catch (cause) { if (alive) setError(hostErrorMessage(cause, "Cannot read media tasks")); }
      finally { if (alive) timer = setTimeout(() => void poll(), 3000); }
    };
    void poll(); return () => { alive = false; clearTimeout(timer); };
  }, [preview, available, sessionId, invoke, refresh]);
  useEffect(() => {
    if (preview || !selected || !sessionId || !available) return;
    let alive = true; let timer: ReturnType<typeof setTimeout>;
    const poll = async () => {
      try { const value = await invoke("media.read", { sessionId, id: selected }); if (!alive) return; setDetail(value); if (active(value.job)) timer = setTimeout(() => void poll(), 2000); else if (value.outputs.length) onArtifactsChanged(); }
      catch (cause) { if (alive) setError(hostErrorMessage(cause, "Cannot read media task")); }
    };
    void poll(); return () => { alive = false; clearTimeout(timer); };
  }, [selected, sessionId, available, preview, invoke, refresh]);
  const run = async (action: (generation: number) => Promise<void>) => { if (lock.current) return; const generation = epoch.current; lock.current = true; setBusy(true); setError(""); try { await action(generation); } catch (cause) { if (generation === epoch.current) setError(hostErrorMessage(cause, "Media operation failed")); } finally { if (generation === epoch.current) { lock.current = false; setBusy(false); } } };
  const matching = models.filter(row => row.kind === type); const choice = matching.find(row => row.selector === model);
  const parameters = useMemo(() => new Set(choice?.parameters ?? (type === "image" ? ["prompt", "inputArtifacts", "aspectRatio", "imageSize"] : type === "speech" ? ["text", "voice", "format"] : type === "transcription" ? ["audioArtifact", "language"] : [])), [choice, type]);
  const show = (name: string) => parameters.has(name); const enabled = preview || (available && !!sessionId && fileChannel);
  const prepare = () => {
    try {
      const optionalNumber = (value: string) => value.trim() ? Number(value) : undefined;
      const fields: Record<string, unknown> = type === "image" ? { prompt, inputArtifacts: picked, aspectRatio: aspect || undefined, imageSize: size || undefined, count: show("count") ? count : undefined }
        : type === "video" ? { prompt: prompt.trim() || undefined, duration: optionalNumber(duration), resolution: resolution || undefined, aspectRatio: aspect || undefined, size: size || undefined, firstFrame: first || undefined, lastFrame: last || undefined, references: picked.map(artifactId => ({ artifactId, type: inputs.find(row => row.artifactId === artifactId)!.kind })), generateAudio: withAudio ? withAudio === "yes" : undefined, seed: optionalNumber(seed), creativity: optionalNumber(creativity), upscaleFactor: optionalNumber(upscale), providerOptions: options.trim() && options.trim() !== "{}" ? JSON.parse(options) : undefined }
          : type === "speech" ? { text, voice: voice || undefined, format, speed: show("speed") ? optionalNumber(speed) : undefined, sampleRate: show("sampleRate") ? optionalNumber(sampleRate) : undefined, bitRate: show("bitRate") ? optionalNumber(bitRate) : undefined, instructions: show("instructions") && instructions.trim() ? instructions : undefined }
            : { audioArtifact: audio, language: language || undefined, prompt: show("prompt") && prompt.trim() ? prompt : undefined, timestamps: show("timestamps") && timestamps !== "none" ? timestamps : undefined, temperature: show("temperature") ? optionalNumber(temperature) : undefined };
      const request: unknown = Object.fromEntries(Object.entries({ type, model: model || undefined, ...fields }).filter(([, value]) => value !== undefined)); validateMediaRequest(request); setReview(request);
    } catch (cause) { setError(hostErrorMessage(cause, "Invalid media request")); }
  };
  const submit = () => void run(async generation => {
    if (!review) return;
    if (preview) { const value: MediaDetail = { ...PREVIEW_MEDIA_DETAIL, job: { ...PREVIEW_MEDIA_DETAIL.job, id: crypto.randomUUID(), type: review.type, model: review.model ?? "demo/role", createdAt: Date.now(), updatedAt: Date.now(), cost: 0 }, request: review, outputs: [], ...(review.type === "transcription" ? { text: PREVIEW_MEDIA_DETAIL.text! } : { text: t("演示任务已完成。真实结果会保存到产物库。", "Demo task completed. Real outputs are saved to the artifact library.") }) }; demos.current.set(value.job.id, value); setJobs(rows => [value.job, ...rows].slice(0, 50)); setSelected(value.job.id); setDetail(value); setReview(undefined); return; }
    const result = await invoke("media.start", { sessionId: sessionId!, request: review });
    if (generation !== epoch.current) return; setSelected(result.job.id); setDetail(undefined); setReview(undefined); setRefresh(value => value + 1);
  });
  const changeType = (next: MediaKind) => { setType(next); setModel(""); setPicked([]); setReview(undefined); setFormat("wav"); };
  const chooseJob = (job: MediaJob) => { setSelected(job.id); setDetail(preview ? demos.current.get(job.id) : undefined); setCloseId(undefined); setError(""); };
  const imagePicker = (label: string, value: string, update: (value: string) => void) => <label>{label}<select className="select" value={value} onChange={event => update(event.target.value)}><option value="">{t("无", "None")}</option>{inputs.filter(row => row.kind === "image").map(row => <option key={row.artifactId} value={row.artifactId}>{row.name}</option>)}</select></label>;
  const inputList = type === "image" ? inputs.filter(row => row.kind === "image") : inputs;
  return <section className="media-workbench" aria-label={t("媒体工作台", "Media workbench")}>
    <div className="media-kind-tabs" role="tablist" aria-label={t("媒体任务类型", "Media task kind")}>{(Object.keys(labels) as MediaKind[]).map(kind => <button className={`btn small ${type === kind ? "primary" : "outline"}`} role="tab" aria-selected={type === kind} key={kind} onClick={() => changeType(kind)}>{labels[kind]}</button>)}{preview ? <span className="chip gray">{t("演示", "Demo")}</span> : null}</div>
    {error ? <p role="alert" className="media-error">{error}</p> : null}{!enabled ? <p className="muted">{t("连接支持私有文件通道的活动 Runtime 后可创建媒体任务。", "Connect an active Runtime with the private media file channel to create tasks.")}</p> : null}
    <div className="media-workbench-layout"><div className="media-request-form">
      <label>{t("模型", "Model")}<select className="select" value={model} onChange={event => { setModel(event.target.value); setFormat("wav"); setReview(undefined); }}><option value="">{type === "video" ? t("请选择视频模型", "Choose a video model") : t("使用原生角色链", "Use the native role chain")}</option>{matching.map(row => <option key={row.selector} value={row.selector}>{row.name} · {row.selector}{row.local ? " · local" : ""}</option>)}</select></label>
      <p className="small muted">{choice ? `${choice.api}${choice.local ? t(" · 本地推理，首次使用可能下载模型", " · Local inference; first use may download weights") : ""}` : t("参数随所选模型传输协议显示。角色链可自动回退；额外尝试也可能计费。", "Parameters follow the selected transport. Native role fallback attempts may also be billed.")}</p>
      {(type === "image" || type === "video" || type === "transcription" && show("prompt")) ? <label>{type === "transcription" ? t("转写提示（可选）", "Transcription hint (optional)") : t("提示词", "Prompt")}<textarea className="input" rows={4} maxLength={32000} value={prompt} onChange={event => setPrompt(event.target.value)} /></label> : null}
      {type === "speech" ? <><label>{t("要朗读的文本", "Text to speak")}<textarea className="input" rows={5} maxLength={15000} value={text} onChange={event => setText(event.target.value)} /></label><div className="media-parameter-grid"><label>{t("音色（留空用默认值）", "Voice (blank uses default)")}<input className="input" value={voice} list="media-voice-options" onChange={event => setVoice(event.target.value)} /><datalist id="media-voice-options">{choice?.voices?.map(voice => <option value={voice.id} key={voice.id}>{voice.label}</option>)}</datalist></label><label>{t("输出格式", "Output format")}<select className="select" value={format} onChange={event => setFormat(event.target.value)}>{(choice?.formats ?? ["wav"]).map(format => <option key={format}>{format}</option>)}</select></label>{show("speed") ? <label>{t("语速（0.25–4）", "Speed (0.25–4)")}<input className="input" type="number" step="0.1" min="0.25" max="4" value={speed} onChange={event => setSpeed(event.target.value)} /></label> : null}{show("sampleRate") ? <label>{t("采样率", "Sample rate")}<input className="input" type="number" value={sampleRate} onChange={event => setSampleRate(event.target.value)} /></label> : null}{show("bitRate") ? <label>{t("比特率", "Bit rate")}<input className="input" type="number" value={bitRate} onChange={event => setBitRate(event.target.value)} /></label> : null}</div>{show("instructions") ? <label>{t("朗读风格说明", "Speech instructions")}<input className="input" maxLength={8000} value={instructions} onChange={event => setInstructions(event.target.value)} /></label> : null}{format === "pcm" ? <p className="small muted">{t("原始 PCM 需要导出到支持的工具播放。", "Raw PCM requires an external player after export.")}</p> : null}</> : null}
      {type === "transcription" ? <><AudioCapturePane workspaceId={workspaceId} sessionId={sessionId} onSaved={artifact => { setInputs(rows => [artifact, ...rows.filter(row => row.artifactId !== artifact.artifactId)]); setAudio(artifact.artifactId); onArtifactsChanged(); }} /><label>{t("音频产物", "Audio artifact")}<select className="select" value={audio} onChange={event => setAudio(event.target.value)}><option value="">{t("选择已导入或录制的音频", "Choose imported or recorded audio")}</option>{inputs.filter(row => row.kind === "audio").map(row => <option key={row.artifactId} value={row.artifactId}>{row.name}</option>)}</select></label><div className="media-parameter-grid"><label>{t("语言代码（可选）", "Language code (optional)")}<input className="input" placeholder="zh / en" maxLength={32} value={language} onChange={event => setLanguage(event.target.value)} /></label>{show("timestamps") ? <label>{t("时间戳", "Timestamps")}<select className="select" value={timestamps} onChange={event => setTimestamps(event.target.value)}><option value="none">{t("无", "None")}</option><option value="segment">{t("段落", "Segments")}</option><option value="word">{t("词", "Words")}</option></select></label> : null}{show("temperature") ? <label>{t("温度", "Temperature")}<input className="input" type="number" min="0" max="1" step="0.1" value={temperature} onChange={event => setTemperature(event.target.value)} /></label> : null}</div></> : null}
      {type === "image" || type === "video" ? <><div className="media-parameter-grid"><label>{t("宽高比（可选）", "Aspect ratio (optional)")}<select className="select" value={aspect} onChange={event => setAspect(event.target.value)}><option value="">{t("默认", "Default")}</option>{["1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3", ...(type === "video" ? ["21:9", "9:21"] : [])].map(value => <option key={value}>{value}</option>)}</select></label><label>{t("尺寸（可选，按模型支持填写）", "Size (optional, model supported)")}<input className="input" placeholder={choice?.api.startsWith("google") ? "1K / 2K / 4K" : "1024x1024"} maxLength={128} value={size} onChange={event => setSize(event.target.value)} /></label>{type === "image" && show("count") ? <label>{t("图片数（1–4）", "Image count (1–4)")}<input className="input" type="number" min={1} max={4} value={count} onChange={event => setCount(Number(event.target.value))} /></label> : null}</div>
        {type === "video" ? <><div className="media-parameter-grid"><label>{t("时长（秒，可选）", "Duration (seconds, optional)")}<input className="input" type="number" min={1} max={120} value={duration} onChange={event => setDuration(event.target.value)} /></label><label>{t("分辨率（可选）", "Resolution (optional)")}<select className="select" value={resolution} onChange={event => setResolution(event.target.value)}><option value="">{t("默认", "Default")}</option>{["360p", "480p", "720p", "768p", "1080p", "1K", "2K", "4K"].map(value => <option key={value}>{value}</option>)}</select></label>{imagePicker(t("首帧", "First frame"), first, setFirst)}{imagePicker(t("尾帧", "Last frame"), last, setLast)}<label>{t("生成音频", "Generate audio")}<select className="select" value={withAudio} onChange={event => setWithAudio(event.target.value)}><option value="">{t("模型默认", "Model default")}</option><option value="yes">{t("是", "Yes")}</option><option value="no">{t("否", "No")}</option></select></label><label>Seed<input className="input" type="number" value={seed} onChange={event => setSeed(event.target.value)} /></label><label>{t("创造性（0–1）", "Creativity (0–1)")}<input className="input" type="number" min={0} max={1} step={0.1} value={creativity} onChange={event => setCreativity(event.target.value)} /></label><label>{t("放大倍数", "Upscale factor")}<input className="input" type="number" min={1} max={4} value={upscale} onChange={event => setUpscale(event.target.value)} /></label></div><details><summary>{t("供应商高级参数", "Provider options")}</summary><textarea className="input mono" maxLength={16000} rows={4} value={options} onChange={event => setOptions(event.target.value)} /></details></> : null}
        <details><summary>{type === "image" ? t("参考图片 / 图片编辑", "Image references / editing") : t("参考图片、音频或视频", "Image, audio or video references")}</summary><div className="media-input-list">{inputList.map(row => <label key={row.artifactId}><input type="checkbox" checked={picked.includes(row.artifactId)} disabled={!picked.includes(row.artifactId) && picked.length >= 8} onChange={event => setPicked(rows => event.target.checked ? [...rows, row.artifactId] : rows.filter(id => id !== row.artifactId))} />{row.name} · {row.kind}</label>)}</div></details>
      </> : null}
      <div className="media-toolbar"><button className="btn small outline" disabled={busy} onClick={() => void run(async () => loadInputs())}>{t("刷新输入产物", "Refresh input artifacts")}</button>{inputCursor ? <button className="btn small outline" disabled={busy} onClick={() => void run(async () => loadInputs(inputCursor))}>{t("加载更多输入产物", "Load more inputs")}</button> : null}<button className="btn small primary" disabled={busy || !enabled || !matching.length} onClick={prepare}>{t("检查生成请求", "Review request")}</button></div>
      <p className="small muted">{t("输入从下方产物库导入；没有内容时不会填入演示数据。", "Import inputs through the artifact library below.")}</p>
    </div><div className="media-job-column">
      <h3>{t("媒体任务", "Media tasks")}</h3><div className="media-job-list">{jobs.map(job => <button key={job.id} className={selected === job.id ? "selected" : ""} onClick={() => chooseJob(job)}><strong>{labels[job.type]}</strong><span>{job.state} · {job.model ?? t("角色链", "Role chain")}</span><small>{new Date(job.createdAt).toLocaleString()} · {job.cost === undefined ? t("费用未知", "Cost unknown") : "$" + job.cost.toFixed(4)}</small></button>)}{!jobs.length ? <p className="muted">{t("暂无任务", "No tasks")}</p> : null}</div>
      {detail ? <section className="media-job-detail"><p className="small mono">{detail.job.id}</p>{detail.job.error ? <p role="status">{detail.job.error}</p> : null}<div className="media-toolbar"><button className="btn small" disabled={busy || !active(detail.job)} onClick={() => void run(async generation => { if (preview) { setDetail(value => value ? { ...value, job: { ...value.job, state: "cancelled" } } : value); return; } await invoke("media.cancel", { sessionId: sessionId!, id: detail.job.id }); if (generation === epoch.current) setRefresh(value => value + 1); })}>{detail.job.type === "video" ? t("停止本地等待", "Stop waiting locally") : t("中止", "Abort")}</button>{detail.job.canResume && !active(detail.job) ? <button className="btn small" disabled={busy} onClick={() => void run(async generation => { if (!preview) await invoke("media.resume", { sessionId: sessionId!, id: detail.job.id }); if (generation === epoch.current) setRefresh(value => value + 1); })}>{t("继续查询原视频任务", "Resume original video job")}</button> : null}<button className="btn small outline" disabled={busy || active(detail.job)} onClick={() => setCloseId(detail.job.id)}>{t("关闭任务记录", "Close task")}</button></div>
        {closeId === detail.job.id ? <div className="media-review"><p>{t("关闭任务记录；已进入产物库的文件会保留。", "Close this task record. Files already in the artifact library remain.")}</p><button className="btn small" disabled={busy} onClick={() => void run(async generation => { if (!preview) await invoke("media.close", { sessionId: sessionId!, id: closeId }); if (generation === epoch.current) { setJobs(rows => rows.filter(job => job.id !== closeId)); setSelected(undefined); setDetail(undefined); setCloseId(undefined); setRefresh(value => value + 1); } })}>{t("确认关闭", "Confirm close")}</button><button className="btn small" onClick={() => setCloseId(undefined)}>{t("返回", "Back")}</button></div> : null}
        {detail.outputs.map(output => <div className="media-job-output" key={output.artifactId}><strong>{output.name}</strong>{!preview && globalThis.ompStudioChrome?.exportArtifact ? output.kind === "image" ? <img src={artifactUrl(output.artifactId)} alt={output.name} /> : output.kind === "video" ? <video src={artifactUrl(output.artifactId)} controls preload="metadata" /> : output.kind === "audio" && output.mimeType !== "audio/pcm" ? <audio src={artifactUrl(output.artifactId)} controls preload="metadata" /> : null : <p className="muted">{preview ? t("演示产物", "Demo artifact") : t("文件预览需桌面文件通道。", "File preview needs the desktop file channel.")}</p>}</div>)}
        {detail.text ? <><textarea className="input" rows={6} readOnly aria-label={t("媒体结果文本", "Media result text")} value={detail.text} />{detail.textTruncated ? <p className="small muted">{t("这里只显示结果摘要，完整转写结果已保存在产物中。", "Showing a bounded excerpt. The transcript artifact holds the full result.")}</p> : null}{detail.job.type === "transcription" ? <button className="btn small primary" disabled={!onInsert} onClick={() => onInsert?.(detail.text!)}>{t("放入主对话输入框", "Insert into main Composer")}</button> : null}</> : null}
      </section> : null}
    </div></div>
    {review ? <section className="media-review" aria-label={t("确认媒体请求", "Confirm media request")}><h3>{labels[review.type]} · {review.model ?? t("原生角色链", "Native role chain")}</h3><p>{t("确认后才向模型提交。云端模型会产生费用，本地模型可能需要下载；视频停止等待不会取消上游任务或费用。", "Confirmation submits the request. Cloud models incur charges; local models may download weights. Stopping video polling does not cancel the provider job or its cost.")}</p>{mediaInputArtifacts(review).length ? <p>{mediaInputArtifacts(review).map(id => inputs.find(row => row.artifactId === id)?.name ?? id).join(" · ")}</p> : null}<pre>{JSON.stringify(review, null, 2)}</pre><button ref={confirm} className="btn small primary" disabled={busy || !enabled} onClick={submit}>{t("确认提交媒体任务", "Confirm media task")}</button><button className="btn small" disabled={busy} onClick={() => setReview(undefined)}>{t("返回修改", "Back to edit")}</button></section> : null}
  </section>;
}
