import {useEffect,useRef,useState} from "react";
import type {CommandInput,StudioClient} from "@omp-studio/client-contract";
import {IDA_VIEWS,type IdaView,type IdaEdit,type IdaState,type IdaResultMap} from "@omp-studio/studio-protocol";
import {usePreviewMode} from "../preview/PreviewContext";
import {useI18n} from "../i18n";
import {waitReceipt,hostErrorMessage} from "../hostError";
import {PREVIEW_IDA,PREVIEW_IDA_TEXT} from "../preview/idaPreview";

export function IdaPane({client,sessionId,available,initialPath}:{client:StudioClient;sessionId:string|undefined;available:boolean;initialPath?:string|undefined}){
 const {preview}=usePreviewMode();const {resolvedLanguage}=useI18n();const zh=resolvedLanguage==="zh";const [supported,setSupported]=useState(false);const [state,setState]=useState<IdaState>();const [dbId,setDbId]=useState("");const [path,setPath]=useState(initialPath??"");const [view,setView]=useState<IdaView>("overview");const [target,setTarget]=useState("");const [action,setAction]=useState<IdaEdit["action"]>("rename");const [value,setValue]=useState("");const [save,setSave]=useState(true);const [repeatable,setRepeatable]=useState(false);const [page,setPage]=useState<IdaResultMap["ida.view"]>();const [review,setReview]=useState<IdaResultMap["ida.prepare"]>();const [result,setResult]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const epoch=useRef(0);const locked=useRef(false);
 const invoke=async<K extends keyof IdaResultMap>(kind:K,input:CommandInput<K>):Promise<IdaResultMap[K]>=>{const handle=await client.command(kind,input as never);return (await waitReceipt<{result:IdaResultMap[K]}>(client,handle.requestId)).result;};
 const run=async(job:(generation:number)=>Promise<void>)=>{if(locked.current)return;locked.current=true;setBusy(true);setError("");const generation=epoch.current;try{await job(generation);}catch(cause){if(generation===epoch.current)setError(hostErrorMessage(cause,zh?"IDA 操作失败":"IDA operation failed"));}finally{locked.current=false;setBusy(false);}};
 const refresh=async(generation:number)=>{const next=preview?structuredClone(PREVIEW_IDA):await invoke("ida.status",{sessionId:sessionId!});if(generation===epoch.current)setState(next);};
 useEffect(()=>{const generation=++epoch.current;setState(preview?structuredClone(PREVIEW_IDA):undefined);setSupported(preview);setReview(undefined);setPage(undefined);setError("");setDbId("");if(!preview&&available&&sessionId)void client.query("capabilities.get",{}).then(async capabilities=>{if(generation!==epoch.current)return;const ok=capabilities.capabilities.some(cap=>cap.id==="ida.status"&&cap.grade!=="unavailable");setSupported(ok);if(ok)await refresh(generation);}).catch(cause=>{if(generation===epoch.current)setError(hostErrorMessage(cause,"IDA unavailable"));});return()=>{epoch.current++;};},[client,sessionId,available,preview]);
 useEffect(()=>setPath(initialPath??""),[initialPath]);
 const db=state?.databases.find(row=>row.id===dbId);const ready=preview||supported&&available&&!!sessionId;const writable=ready&&state?.available&&!!db?.identity&&db.version!==undefined;
 const prepare=(edit:IdaEdit)=>void run(async generation=>{const next=preview?{token:"demo",edit,...(db?.identity?{identity:db.identity,version:db.version!}:{}),expiresAt:Date.now()+300000}:await invoke("ida.prepare",{sessionId:sessionId!,edit});if(generation===epoch.current)setReview(next);});
 const buildEdit=():IdaEdit=>{if(action==="open")return {action,path};if(action==="close")return {action,dbId,save};if(action==="save")return {action,dbId};if(action==="exec")return {action,dbId,code:value};if(action==="rename")return {action,dbId,target,name:value};if(action==="set_type")return {action,dbId,target,decl:value};if(action==="comment")return {action,dbId,target,text:value,repeatable};return {action,dbId,target};};
 const read=(offset=0)=>void run(async generation=>{const next=preview?{text:PREVIEW_IDA_TEXT,total:4,offset:0,truncated:false}:await invoke("ida.view",{sessionId:sessionId!,dbId,identity:db!.identity!,version:db!.version!,view,...(target?{target}:{}),offset});if(generation===epoch.current)setPage(next);});
 return <section style={{display:"grid",gap:10,alignContent:"start"}} className="runtime-catalog-pane" aria-label="IDA"><h3>IDA {preview?(zh?"· 演示":"· Demo"):""}</h3><p className="muted">{zh?"需要已安装并授权的 IDA Pro/idalib 与匹配的 Python。请在设置中填写 IDA 安装目录和 Python 路径；Studio 不会自动安装商业软件。":"Requires licensed IDA Pro/idalib and a matching Python. Configure the IDA installation and Python paths in Settings. Studio does not install commercial software."}</p>
  {!ready?<p role="status">{zh?"当前 Runtime 不支持 IDA 面板或尚未连接":"This Runtime does not support the IDA panel or is disconnected"}</p>:null}{state?.reason?<p role="status">{state.reason}</p>:null}{error?<p role="alert">{error}</p>:null}
  <button className="btn outline" disabled={!ready||busy} onClick={()=>void run(refresh)}>{zh?"检测 / 刷新":"Detect / refresh"}</button>
  <label style={{display:"grid",gap:6}}>{zh?"二进制 / 数据库路径":"Binary / database path"}<input className="input" value={path} onChange={event=>setPath(event.target.value)}/></label><button className="btn" disabled={!ready||!state?.available||busy||!path.trim()} onClick={()=>prepare({action:"open",path})}>{zh?"检查打开操作":"Review open"}</button>
  <select className="select" aria-label={zh?"IDA 数据库":"IDA database"} value={dbId} onChange={event=>{setDbId(event.target.value);setPage(undefined);setReview(undefined);}}><option value="">{zh?"选择数据库":"Select database"}</option>{state?.databases.map(row=><option key={row.id} value={row.id}>{row.label} · {row.state}{row.dirty?" *":""}</option>)}</select>
  {db?<p className="small muted">{db.identity??(zh?"此 IDA 主机不支持版本校验":"This IDA host lacks version fencing")} · v{db.version??"?"}{db.busy?" · busy":""}</p>:null}
  <label style={{display:"grid",gap:6}}>{zh?"地址 / 符号":"Address / symbol"}<input className="input" value={target} onChange={event=>setTarget(event.target.value)} placeholder="0x140001000 / main"/></label>
  <select className="select" aria-label={zh?"IDA 视图":"IDA view"} value={view} onChange={event=>setView(event.target.value as IdaView)}>{IDA_VIEWS.map(id=><option key={id} value={id}>{id}</option>)}</select><button className="btn" disabled={!writable||busy} onClick={()=>read()}>{zh?"读取":"Read"}</button>
  {page?<><pre style={{maxHeight:400,overflow:"auto",whiteSpace:"pre-wrap"}}>{page.text}</pre><p>{page.offset} / {page.total}{page.truncated?" · truncated":""}</p><button className="btn" disabled={busy||page.nextOffset===undefined} onClick={()=>read(page.nextOffset)}>{zh?"下一页":"Next page"}</button></>:null}
  <hr/><select className="select" aria-label={zh?"IDA 操作":"IDA action"} value={action} onChange={event=>setAction(event.target.value as IdaEdit["action"])}>{["rename","comment","set_type","make_function","exec","save","close"].map(id=><option key={id}>{id}</option>)}</select>
  {["rename","comment","set_type","exec"].includes(action)?<textarea className="input mono" aria-label={zh?"操作内容":"Operation content"} rows={action==="exec"?8:3} value={value} onChange={event=>setValue(event.target.value)} placeholder={action==="exec"?"# Python; db is the ida_domain Database":""}/>:null}
  {action==="comment"?<label style={{display:"grid",gap:6}}><input type="checkbox" checked={repeatable} onChange={event=>setRepeatable(event.target.checked)}/>{zh?"可重复注释":"Repeatable comment"}</label>:null}{action==="close"?<label style={{display:"grid",gap:6}}><input type="checkbox" checked={save} onChange={event=>setSave(event.target.checked)}/>{zh?"关闭前保存":"Save before closing"}</label>:null}
  <button className="btn outline" disabled={!writable||busy} onClick={()=>prepare(buildEdit())}>{zh?"检查操作":"Review operation"}</button>
  {review?<section role="alertdialog" aria-label={zh?"确认 IDA 操作":"Confirm IDA operation"}><pre style={{whiteSpace:"pre-wrap",maxHeight:300,overflow:"auto"}}>{JSON.stringify(review.edit,null,2)}</pre><p>{review.identity??path} · v{review.version??"new"}</p>{review.edit.action==="exec"?<p>{zh?"Python 可修改数据库并访问本机资源，请核对完整代码。":"Python can modify the database and access local resources. Review the full code."}</p>:null}<button className="btn primary" disabled={busy||Date.now()>review.expiresAt} onClick={()=>void run(async generation=>{if(preview){setResult(zh?"演示操作已完成":"Demo operation completed");setState(current=>({...current!,databases:review.edit.action==="close"?current!.databases.filter(row=>row.id!==dbId):current!.databases.map(row=>row.id===dbId?{...row,version:(row.version??0)+1,dirty:review.edit.action!=="save"}:row)}));setReview(undefined);return;}const outcome=await invoke("ida.commit",{sessionId:sessionId!,token:review.token});if(generation===epoch.current){setResult(outcome.text);setReview(undefined);setPage(undefined);await refresh(generation);}})}>{zh?"确认执行":"Confirm execution"}</button><button className="btn" disabled={busy} onClick={()=>setReview(undefined)}>{zh?"返回":"Back"}</button></section>:null}
  {busy?<button className="btn" onClick={()=>{if(!preview&&sessionId)void invoke("ida.cancel",{sessionId}).catch(cause=>setError(hostErrorMessage(cause,"Cancel failed")));}}>{zh?"取消等待 / 执行":"Cancel wait / execution"}</button>:null}{result?<pre style={{whiteSpace:"pre-wrap"}}>{result}</pre>:null}
 </section>;
}
