import {useEffect,useRef,useState} from "react";
import type {StudioClient} from "@omp-studio/client-contract";
import type {ResourcePage} from "@omp-studio/studio-protocol";
import {usePreviewMode} from "../preview/PreviewContext";
import {useI18n} from "../i18n";
import {hostErrorMessage,waitReceipt} from "../hostError";
import {PREVIEW_RESOURCE} from "../preview/resourcesPreview";
export function ResourcesPane({client,sessionId,available}:{client:StudioClient;sessionId:string|undefined;available:boolean}){
 const {preview}=usePreviewMode();const {resolvedLanguage}=useI18n();const zh=resolvedLanguage==="zh";const [uri,setUri]=useState("omp://");const [page,setPage]=useState<ResourcePage>();const [busy,setBusy]=useState(false);const [supported,setSupported]=useState(false);const [error,setError]=useState("");const epoch=useRef(0);const lock=useRef(false);
 useEffect(()=>{const generation=++epoch.current;setPage(preview?PREVIEW_RESOURCE:undefined);setSupported(preview);setError("");if(!preview&&available&&sessionId)void client.query("capabilities.get",{}).then(value=>{if(generation===epoch.current)setSupported(value.capabilities.some(cap=>cap.id==="resource.read"&&cap.grade!=="unavailable"));}).catch(()=>{});return()=>{epoch.current++;};},[client,sessionId,available,preview]);
 const read=async(next=false)=>{if(lock.current)return;const generation=epoch.current;lock.current=true;setBusy(true);setError("");try{let result:ResourcePage;if(preview)result={...PREVIEW_RESOURCE,uri};else{if(!sessionId||!available||!supported)throw Error("Resource capability unavailable");const handle=await client.command("resource.read",{sessionId,uri:next?page!.uri:uri,...(next?{offset:page!.nextOffset!,version:page!.version}:{})});result=(await waitReceipt<{result:ResourcePage}>(client,handle.requestId)).result;}if(generation===epoch.current)setPage(result);}catch(cause){if(generation===epoch.current)setError(hostErrorMessage(cause,zh?"资源读取失败":"Resource read failed"));}finally{lock.current=false;setBusy(false);}};
 return <section style={{display:"grid",gap:10,alignContent:"start"}} className="runtime-catalog-pane"><h3>{zh?"会话资源":"Session resources"}{preview?" · Demo":""}</h3><p className="muted">{zh?"资源绑定当前活动会话；分页会校验内容版本。支持 local://、omp://、attachment:// 和 conflict://。":"Resources belong to the active session; paging verifies content versions. Supports local://, omp://, attachment:// and conflict://."} · {sessionId??"—"}</p>{!supported?<p role="status">{zh?"当前 Runtime 未提供资源查看能力":"This Runtime does not support resource viewing"}</p>:null}<form onSubmit={event=>{event.preventDefault();void read();}}><input className="input mono" aria-label="Resource URI" value={uri} onChange={event=>setUri(event.target.value)} placeholder="local://notes.md"/><button className="btn" disabled={busy||!supported}>{zh?"读取":"Read"}</button></form>{error?<p role="alert">{error}</p>:null}{page?<><p className="small muted">{page.uri} · {page.offset}/{page.total}{page.truncated?" · truncated":""}</p>{page.image?<img alt={page.uri} src={`data:${page.image.mimeType};base64,${page.image.data}`} style={{maxWidth:"100%",maxHeight:500}}/>:null}<pre style={{whiteSpace:"pre-wrap",maxHeight:600,overflow:"auto"}}>{page.text}</pre><button className="btn" disabled={busy||page.nextOffset===undefined} onClick={()=>void read(true)}>{zh?"下一页":"Next page"}</button></>:null}</section>;
}
