/**
 * Desktop managed Runtime install seam.
 *
 * `runtime.install` copies a locally signed artifact into the Host-owned
 * Runtime tree and activates it. There is no downloader and no PATH /
 * system-omp fallback. Artifact lookup is Host-only; paths never enter
 * ClientBootstrap.
 *
 * Unpackaged (`electron .`) keeps that tree under
 * `%APPDATA%\omp-studio\runtimes`. Packaged builds put the live
 * `omp.exe` at `$INSTDIR\runtime\versions\<ver>\` (`extraFiles` already
 * uses the installer layout). First launch verifies and writes
 * `$INSTDIR\runtime\current.json`; diagnostics updates write the same
 * folder. Uninstall deletes that live Runtime with the app.
 */

import { readFile, readdir } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { HostRuntimeInstallProbe, HostRuntimeInstallService } from "@omp-studio/host-client-api";
import type { RuntimeChannel, RuntimeInstallState, SignatureStatus } from "@omp-studio/client-contract";
import {
  isInside,
  parseRuntimeInstallationManifest,
  type ActivateOptions,
  type RuntimeInstallOptions,
} from "@omp-studio/runtime-installer";
import type { HostBackend } from "@omp-studio/studio-host";
import type { RuntimeInstallationManifest } from "@omp-studio/studio-protocol";

export interface LocateManagedRuntimeArtifactOptions {
  readonly channel?: RuntimeChannel;
  readonly platform: string;
  readonly roots?: readonly string[];
}

const DEFAULT_RUNTIME_CHANNEL: RuntimeChannel = "stable";

interface ParsedRuntimeVersion {
  readonly core: readonly [number, number, number];
  readonly prerelease: readonly (number | string)[];
}

/** Match the RuntimeInstaller directory-name guard without requiring semver. */
function isSafeRuntimeVersion(value: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(value);
}

/**
 * Parse the semver-shaped versions generated by `runtime-artifact.mjs`.
 *
 * Runtime versions are `<upstreamVersion>-<patchsetVersion>` (for example
 * `18.0.3-studio.1`). Keeping this parser local avoids a locale-dependent
 * ordering. Legacy directory-safe versions such as `v1` remain discoverable;
 * they simply have no semantic ordering against another non-semver version.
 */
function parseRuntimeVersion(value: string): ParsedRuntimeVersion | undefined {
  const match = /^(?:v)?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/u.exec(value);
  if (match === null) return undefined;
  const core = [Number(match[1]), Number(match[2]), Number(match[3])] as const;
  if (core.some((part) => !Number.isSafeInteger(part))) return undefined;
  const prerelease: Array<number | string> = [];
  for (const identifier of match[4]?.split(".") ?? []) {
    if (/^(0|[1-9]\d*)$/u.test(identifier)) {
      const numeric = Number(identifier);
      if (!Number.isSafeInteger(numeric)) return undefined;
      prerelease.push(numeric);
    } else {
      prerelease.push(identifier);
    }
  }
  return {
    core,
    prerelease,
  };
}

export function compareRuntimeVersions(left: string, right: string): number | undefined {
  const leftParsed = parseRuntimeVersion(left);
  const rightParsed = parseRuntimeVersion(right);
  if (leftParsed === undefined || rightParsed === undefined) return undefined;
  for (let index = 0; index < leftParsed.core.length; index += 1) {
    const leftPart = leftParsed.core[index] ?? 0;
    const rightPart = rightParsed.core[index] ?? 0;
    if (leftPart !== rightPart) return leftPart - rightPart;
  }
  if (leftParsed.prerelease.length === 0 || rightParsed.prerelease.length === 0) {
    if (leftParsed.prerelease.length === rightParsed.prerelease.length) return 0;
    return leftParsed.prerelease.length === 0 ? 1 : -1;
  }
  const length = Math.max(leftParsed.prerelease.length, rightParsed.prerelease.length);
  for (let index = 0; index < length; index += 1) {
    const leftPart = leftParsed.prerelease[index];
    const rightPart = rightParsed.prerelease[index];
    if (leftPart === undefined) return -1;
    if (rightPart === undefined) return 1;
    if (leftPart === rightPart) continue;
    if (typeof leftPart === "number" && typeof rightPart === "number") return leftPart - rightPart;
    if (typeof leftPart === "number") return -1;
    if (typeof rightPart === "number") return 1;
    return leftPart < rightPart ? -1 : 1;
  }
  return 0;
}

function effectiveRuntimeChannel(channel: RuntimeChannel | undefined): RuntimeChannel {
  return channel ?? DEFAULT_RUNTIME_CHANNEL;
}

export interface PendingArtifactRegistry {
  /** 已验签、可直接交给 RuntimeInstaller.install() 的目录；无则 undefined。 */
  peek(): string | undefined;
  set(directory: string | undefined): void;
}

export function createPendingArtifactRegistry(): PendingArtifactRegistry {
  let pending: string | undefined;
  return {
    peek() {
      return pending;
    },
    set(directory) {
      pending = directory;
    },
  };
}

export interface DesktopManagedInstallOptions {
  readonly locateArtifact?: (input: LocateManagedRuntimeArtifactOptions) => Promise<string | undefined>;
  readonly activateOptions?: ActivateOptions;
  /** Tests replace the post-activate Runtime start; production leaves this unset. */
  readonly afterActivate?: () => Promise<void>;
  /**
   * Host `RuntimeInstaller` root. Packaged: `$INSTDIR\runtime`. Unpackaged:
   * omitted so HostBackend uses `%APPDATA%\omp-studio\runtimes`.
   */
  readonly installDirectory?: string;
  /**
   * Signed artifact lookup root. Packaged: `$INSTDIR\runtime\versions`
   * (the live version folders). Prepended when `locateArtifact` is not
   * overridden.
   */
  readonly artifactRoot?: string;
  /** Packaged public verification key dir (`$INSTDIR\runtime-keys`). Never the private key. */
  readonly trustedKeysDirectory?: string;
  /**
   * When no current managed install exists, copy+activate the located
   * artifact into the installer root before the first resolve. Packaged
   * extraFiles already land under `versions/`, so this is verify +
   * `current.json`. Failures stay read-only.
   */
  readonly seedOnStart?: boolean;
  readonly pendingArtifact?: PendingArtifactRegistry;
}

export const PACKAGED_RUNTIME_ARTIFACT_DIR = "runtime";
export const PACKAGED_RUNTIME_VERSIONS_DIR = "versions";
export const PACKAGED_RUNTIME_KEYS_DIR = "runtime-keys";

/** Layout written next to the packaged `OMP Studio.exe`. Undefined when unpackaged. */
export function packagedRuntimeInstallLayout(input: {
  readonly isPackaged: boolean;
  readonly execPath: string;
}): { readonly installDirectory: string; readonly artifactRoot: string; readonly keysDirectory: string } | undefined {
  if (!input.isPackaged) return undefined;
  const installDir = dirname(input.execPath);
  const installDirectory = join(installDir, PACKAGED_RUNTIME_ARTIFACT_DIR);
  return {
    installDirectory,
    artifactRoot: join(installDirectory, PACKAGED_RUNTIME_VERSIONS_DIR),
    keysDirectory: join(installDir, PACKAGED_RUNTIME_KEYS_DIR),
  };
}

/** Host RuntimeInstaller root: packaged override, otherwise `<state>/runtimes`. */
export function resolveManagedRuntimeInstallDirectory(input: {
  readonly stateDirectory: string;
  readonly installDirectory?: string;
}): string {
  const override = input.installDirectory?.trim();
  if (override !== undefined && override.length > 0) return override;
  return join(input.stateDirectory, "runtimes");
}

const TRUSTED_KEYS_FILE = "trusted-keys.json";
const KEY_ID_FILE = "key-id.txt";
const PUBLIC_KEY_FILE = "trusted-public.pem";

/** Host-profile key directory. Never a repository path. */
export function defaultRuntimeKeysDirectory(): string {
  if (process.platform === "darwin") {
    return join(homedir(), "Library", "Application Support", "omp-studio", "keys");
  }
  return join(process.env.APPDATA ?? join(homedir(), "AppData", "Roaming"), "omp-studio", "keys");
}

async function readTrustedKeysDirectory(
  keysDirectory: string,
): Promise<{ trustedKeys: Record<string, Buffer> } | undefined> {
  // First, try trusted-keys.json (multi-key table)
  try {
    const raw = JSON.parse(await readFile(join(keysDirectory, TRUSTED_KEYS_FILE), "utf8")) as unknown;
    if (raw && typeof raw === "object" && "keys" in raw && raw.keys && typeof raw.keys === "object") {
      const keysObj = raw.keys as Record<string, unknown>;
      const trustedKeys: Record<string, Buffer> = {};
      for (const [keyId, fileName] of Object.entries(keysObj)) {
        if (typeof fileName !== "string" || fileName.trim().length === 0) continue;
        const resolvedPath = join(keysDirectory, fileName);
        if (!isInside(keysDirectory, resolvedPath)) continue;
        try {
          const buf = await readFile(resolvedPath);
          if (buf.length > 0) {
            trustedKeys[keyId] = buf;
          }
        } catch {
          // Skip invalid/unreadable key file without breaking the table
        }
      }
      if (Object.keys(trustedKeys).length > 0) {
        return { trustedKeys };
      }
    }
  } catch {
    // If trusted-keys.json does not exist or fails to parse, fall back to legacy format
  }

  // Fallback: legacy key-id.txt + trusted-public.pem
  try {
    const keyId = (await readFile(join(keysDirectory, KEY_ID_FILE), "utf8")).trim();
    const publicKey = await readFile(join(keysDirectory, PUBLIC_KEY_FILE));
    if (keyId.length === 0 || publicKey.length === 0) {
      return undefined;
    }
    return { trustedKeys: { [keyId]: publicKey } };
  } catch {
    return undefined;
  }
}

export async function loadInstallerTrustedKeys(
  keysDirectory: string | readonly string[] = defaultRuntimeKeysDirectory(),
): Promise<{ trustedKeys: Record<string, Buffer> } | undefined> {
  const envPath = process.env.OMP_RUNTIME_TRUSTED_PUBLIC_KEY?.trim();
  const envId = process.env.OMP_RUNTIME_SIGNING_KEY_ID?.trim();
  if (envPath !== undefined && envPath.length > 0 && envId !== undefined && envId.length > 0) {
    return { trustedKeys: { [envId]: await readFile(envPath) } };
  }
  const directories = typeof keysDirectory === "string" ? [keysDirectory] : keysDirectory;
  for (const directory of directories) {
    const loaded = await readTrustedKeysDirectory(directory);
    if (loaded !== undefined) return loaded;
  }
  return undefined;
}

const ARTIFACT_WALK_DEPTH = 8;

function artifactRootFor(base: string, platform: string): string {
  return join(base, "packages", "runtime-installer", "dist", "artifacts", platform);
}

/**
 * Electron `npm run dev -w @omp-studio/desktop` sets cwd to `apps/desktop`,
 * not the repo root. Walk ancestors of each seed so a locally built
 * `packages/runtime-installer/dist/artifacts/<platform>` tree is found.
 */
export function collectManagedRuntimeArtifactRoots(options: {
  readonly platform: string;
  readonly seeds: readonly string[];
  readonly extra?: string;
}): string[] {
  const seen = new Set<string>();
  const roots: string[] = [];
  const add = (directory: string): void => {
    const resolved = resolve(directory);
    if (seen.has(resolved)) {
      return;
    }
    seen.add(resolved);
    roots.push(resolved);
  };
  const extra = options.extra?.trim();
  if (extra !== undefined && extra.length > 0) {
    add(extra);
  }
  for (const seed of options.seeds) {
    let directory = resolve(seed);
    for (let depth = 0; depth < ARTIFACT_WALK_DEPTH; depth += 1) {
      add(artifactRootFor(directory, options.platform));
      const parent = dirname(directory);
      if (parent === directory) {
        break;
      }
      directory = parent;
    }
  }
  return roots;
}

function defaultArtifactRoots(platform: string, extra?: string): string[] {
  const fromEnv = process.env.OMP_ARTIFACT_DIR;
  const resolvedExtra = extra ?? fromEnv;
  return collectManagedRuntimeArtifactRoots({
    platform,
    seeds: [process.cwd(), fileURLToPath(new URL(".", import.meta.url))],
    ...(resolvedExtra === undefined ? {} : { extra: resolvedExtra }),
  });
}

export function createManagedArtifactLocator(options: {
  readonly artifactRoot?: string;
  readonly locateArtifact?: (input: LocateManagedRuntimeArtifactOptions) => Promise<string | undefined>;
  readonly pendingArtifact?: PendingArtifactRegistry;
}): (input: LocateManagedRuntimeArtifactOptions) => Promise<string | undefined> {
  if (options.locateArtifact !== undefined) return options.locateArtifact;

  const artifactRoot = options.artifactRoot;
  const fallback =
    artifactRoot === undefined
      ? locateManagedRuntimeArtifact
      : (input: LocateManagedRuntimeArtifactOptions) =>
          locateManagedRuntimeArtifact({
            ...input,
            roots: [resolve(artifactRoot)],
          });

  return async (input) => {
    const pendingDir = options.pendingArtifact?.peek();
    if (pendingDir !== undefined) {
      const manifest = await readArtifactManifest(pendingDir);
      if (manifest !== undefined && matchesArtifact(manifest, input)) {
        return pendingDir;
      }
    }
    return fallback(input);
  };
}

async function readArtifactManifest(directory: string): Promise<RuntimeInstallationManifest | undefined> {
  try {
    return parseRuntimeInstallationManifest(JSON.parse(await readFile(join(directory, "runtime-manifest.json"), "utf8")));
  } catch {
    return undefined;
  }
}

function matchesArtifact(
  manifest: RuntimeInstallationManifest,
  options: LocateManagedRuntimeArtifactOptions,
): boolean {
  if (manifest.platform !== options.platform) {
    return false;
  }
  if (manifest.channel !== effectiveRuntimeChannel(options.channel)) {
    return false;
  }
  return isSafeRuntimeVersion(manifest.runtimeVersion);
}

/** Newest matching signed artifact directory, or `undefined` when none exist. */
export async function locateManagedRuntimeArtifact(
  options: LocateManagedRuntimeArtifactOptions,
): Promise<string | undefined> {
  const roots = options.roots ?? defaultArtifactRoots(options.platform);
  const matches: Array<{ directory: string; version: string }> = [];
  for (const root of roots) {
    const direct = await readArtifactManifest(root);
    if (direct !== undefined) {
      if (matchesArtifact(direct, options)) {
        matches.push({ directory: root, version: direct.runtimeVersion });
      }
      continue;
    }
    let entries;
    try {
      entries = await readdir(root, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name.startsWith(".")) {
        continue;
      }
      const directory = join(root, entry.name);
      const manifest = await readArtifactManifest(directory);
      if (manifest === undefined || !matchesArtifact(manifest, options)) {
        continue;
      }
      matches.push({ directory, version: manifest.runtimeVersion });
    }
  }
  if (matches.length === 0) {
    return undefined;
  }
  matches.sort((left, right) => {
    const versionOrder = compareRuntimeVersions(left.version, right.version);
    if (versionOrder !== undefined && versionOrder !== 0) return versionOrder;
    if (left.version !== right.version) return left.version < right.version ? -1 : 1;
    if (left.directory === right.directory) return 0;
    return left.directory < right.directory ? -1 : 1;
  });
  return matches[matches.length - 1]?.directory;
}

/**
 * Compare an installed runtime version against a locally discovered
 * artifact. Uses the same semantic-version order as artifact locate.
 * Paths never enter the returned read model.
 */
export function resolveManagedRuntimeInstallState(input: {
  readonly installedVersion?: string;
  readonly availableVersion?: string;
  readonly signature?: SignatureStatus;
}): RuntimeInstallState {
  const signature = input.signature ?? "unknown";
  const installed = input.installedVersion;
  const available =
    input.availableVersion !== undefined && isSafeRuntimeVersion(input.availableVersion)
      ? input.availableVersion
      : undefined;
  if (installed === undefined) {
    return available === undefined
      ? { status: "not-installed", signature }
      : { status: "not-installed", signature, availableVersion: available };
  }
  const availableOrder = available === undefined ? undefined : compareRuntimeVersions(available, installed);
  if (available !== undefined && availableOrder !== undefined && availableOrder > 0) {
    return {
      status: "update-available",
      version: installed,
      availableVersion: available,
      signature,
    };
  }
  if (available !== undefined && availableOrder === undefined) {
    return { status: "installed", version: installed, availableVersion: available, signature };
  }
  return { status: "installed", version: installed, signature };
}

export type SeedManagedRuntimeResult = "seeded" | "already-installed" | "skipped";

export interface SeedManagedRuntimeBackend {
  readonly installer: {
    currentManifest(): Promise<unknown>;
  };
  install(directory: string): Promise<RuntimeInstallationManifest>;
  activate(version: string, options?: ActivateOptions): Promise<unknown>;
}

/**
 * Copy the shipped/located signed artifact into the Host installer root
 * when nothing is current. Does not start a Runtime session. When the
 * artifact already is that versions folder, install is a no-op and this
 * only activates.
 */
export async function seedManagedRuntimeFromArtifact(options: {
  readonly backend: SeedManagedRuntimeBackend;
  readonly platform: string;
  readonly hasTrustedKey: boolean;
  readonly channel?: RuntimeChannel;
  readonly locateArtifact?: (input: LocateManagedRuntimeArtifactOptions) => Promise<string | undefined>;
  readonly activateOptions?: ActivateOptions;
}): Promise<SeedManagedRuntimeResult> {
  if (!options.hasTrustedKey) return "skipped";
  let current;
  try {
    current = await options.backend.installer.currentManifest();
  } catch {
    current = undefined;
  }
  if (current !== undefined) return "already-installed";
  const locate = options.locateArtifact ?? locateManagedRuntimeArtifact;
  const channel = effectiveRuntimeChannel(options.channel);
  const artifactDirectory = await locate({ platform: options.platform, channel });
  if (artifactDirectory === undefined) return "skipped";
  const locatedManifest = await readArtifactManifest(artifactDirectory);
  if (locatedManifest !== undefined && locatedManifest.channel !== channel) {
    throw new Error(`Managed Runtime artifact channel mismatch: expected ${channel}`);
  }
  const manifest = await options.backend.install(artifactDirectory);
  if (manifest.channel !== channel) {
    throw new Error(`Managed Runtime artifact channel mismatch: expected ${channel}`);
  }
  await options.backend.activate(manifest.runtimeVersion, options.activateOptions);
  return "seeded";
}

export async function probeManagedRuntimeInstall(options: {
  readonly platform: string;
  readonly currentVersion?: string;
  readonly channel?: RuntimeChannel;
  readonly locateArtifact?: (input: LocateManagedRuntimeArtifactOptions) => Promise<string | undefined>;
}): Promise<RuntimeInstallState> {
  const locate = options.locateArtifact ?? locateManagedRuntimeArtifact;
  const channel = effectiveRuntimeChannel(options.channel);
  const directory = await locate({
    platform: options.platform,
    channel,
  });
  let availableVersion: string | undefined;
  if (directory !== undefined) {
    const manifest = await readArtifactManifest(directory);
    if (manifest?.channel === channel && isSafeRuntimeVersion(manifest.runtimeVersion)) {
      availableVersion = manifest.runtimeVersion;
    }
  }
  return resolveManagedRuntimeInstallState({
    ...(options.currentVersion === undefined ? {} : { installedVersion: options.currentVersion }),
    ...(availableVersion === undefined ? {} : { availableVersion }),
  });
}

export function createDesktopRuntimeInstallProbe(options: {
  readonly backend: Pick<HostBackend, "installer">;
  readonly platform: string;
  readonly channel?: RuntimeChannel;
  readonly locateArtifact?: (input: LocateManagedRuntimeArtifactOptions) => Promise<string | undefined>;
  readonly artifactRoot?: string;
  readonly pendingArtifact?: PendingArtifactRegistry;
}): HostRuntimeInstallProbe {
  const locate = createManagedArtifactLocator(options);
  return async (): Promise<RuntimeInstallState> => {
    let currentVersion: string | undefined;
    try {
      currentVersion = (await options.backend.installer.currentManifest())?.manifest.runtimeVersion;
    } catch {
      currentVersion = undefined;
    }
    return probeManagedRuntimeInstall({
      platform: options.platform,
      channel: effectiveRuntimeChannel(options.channel),
      ...(currentVersion === undefined ? {} : { currentVersion }),
      locateArtifact: locate,
    });
  };
}

export function createDesktopRuntimeInstallService(options: {
  readonly backend: Pick<HostBackend, "install" | "activate">;
  readonly platform: string;
  readonly hasTrustedKey: boolean;
  readonly locateArtifact?: (input: LocateManagedRuntimeArtifactOptions) => Promise<string | undefined>;
  readonly artifactRoot?: string;
  readonly activateOptions?: ActivateOptions;
  readonly installOptions?: RuntimeInstallOptions;
  readonly afterActivate?: (manifest: RuntimeInstallationManifest) => Promise<void>;
  readonly pendingArtifact?: PendingArtifactRegistry;
}): HostRuntimeInstallService {
  const locate = createManagedArtifactLocator(options);
  return async (channel?: RuntimeChannel): Promise<RuntimeInstallState> => {
    const pendingAtStart = options.pendingArtifact?.peek();
    try {
      if (!options.hasTrustedKey) {
        throw new Error(
          "Managed Runtime install requires OMP_RUNTIME_TRUSTED_PUBLIC_KEY and OMP_RUNTIME_SIGNING_KEY_ID. Run npm run omp:keys to create a local signing key.",
        );
      }
      const selectedChannel = effectiveRuntimeChannel(channel);
      const artifactDirectory = await locate({
        platform: options.platform,
        channel: selectedChannel,
      });
      if (artifactDirectory === undefined) {
        throw new Error(
          channel === undefined
            ? "No managed Runtime artifact was found. Run npm run omp:build:host or set OMP_ARTIFACT_DIR."
            : `No managed Runtime artifact was found for the ${selectedChannel} channel.`,
        );
      }
      const locatedManifest = await readArtifactManifest(artifactDirectory);
      if (locatedManifest !== undefined && locatedManifest.channel !== selectedChannel) {
        throw new Error(`Managed Runtime artifact channel mismatch: expected ${selectedChannel}`);
      }
      const manifest = await options.backend.install(artifactDirectory, options.installOptions);
      if (manifest.channel !== selectedChannel) {
        throw new Error(`Managed Runtime artifact channel mismatch: expected ${selectedChannel}`);
      }
      await options.backend.activate(manifest.runtimeVersion, options.activateOptions);
      try {
        await options.afterActivate?.(manifest);
      } catch (error) {
        return {
          status: "failed",
          version: manifest.runtimeVersion,
          signature: "verified",
          message: error instanceof Error ? error.message : "Runtime did not start",
        };
      }
      return {
        status: "installed",
        version: manifest.runtimeVersion,
        signature: "verified",
      };
    } finally {
      if (options.pendingArtifact?.peek() === pendingAtStart) {
        options.pendingArtifact?.set(undefined);
      }
    }
  };
}
