import {useEffect,useRef,useState} from "react";
import type {AskImage} from "@omp-studio/studio-protocol";
import {fileToPromptImage,imagePreviewUrl} from "../composer/ingest";

export async function askImage(file:File):Promise<AskImage>{
 if(!["image/png","image/jpeg","image/gif","image/webp"].includes(file.type)||file.size>20*1024*1024)throw Error("Choose PNG, JPEG, GIF or WebP under 20 MB / 请选择 20 MB 以内的图片");
 if(file.size<=96*1024)return (await fileToPromptImage(file)) as AskImage;
 const bitmap=await createImageBitmap(file);try{const canvas=document.createElement("canvas");for(const edge of [1280,800,480]){const scale=Math.min(1,edge/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext("2d")!;context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",0.7));if(blob&&blob.size<=96*1024)return (await fileToPromptImage(new File([blob],"attachment.jpg",{type:"image/jpeg"}))) as AskImage;}throw Error("Image exceeds response budget / 图片超出回答容量");}finally{bitmap.close();}
}
export function AskImages({images,onChange,disabled,label,files,onBusy}:{images:readonly AskImage[];onChange:(images:readonly AskImage[])=>void;disabled?:boolean|undefined;label:string;files?:readonly File[]|undefined;onBusy?:(busy:boolean)=>void}){
 const [error,setError]=useState("");const [preview,setPreview]=useState<AskImage>();const [busy,setBusy]=useState(false);const epoch=useRef(0);const input=useRef<HTMLInputElement>(null);const current=useRef(images);current.current=images;
 useEffect(()=>()=>{epoch.current++;},[]);
 useEffect(()=>{onBusy?.(busy);return()=>onBusy?.(false);},[busy,onBusy]);
 const add=async(next:readonly File[])=>{if(disabled||busy)return;const generation=epoch.current;setBusy(true);try{if(current.current.length+next.length>4)throw Error("At most 4 images per answer field / 每个回答区最多 4 张图片");const added=[];for(const file of next)added.push(await askImage(file));if(epoch.current===generation){onChange([...current.current,...added]);setError("");}}catch(cause){if(epoch.current===generation)setError(String(cause));}finally{if(epoch.current===generation)setBusy(false);}};
 useEffect(()=>{if(files?.length)void add(files);},[files]);
 return <div className="ask-images" style={{display:"flex",alignItems:"center",flexWrap:"wrap",gap:8}}><input ref={input} type="file" accept="image/png,image/jpeg,image/gif,image/webp" multiple hidden onChange={event=>{void add([...event.target.files??[]]);event.target.value="";}}/><button type="button" className="btn small outline" disabled={disabled||busy} onClick={()=>input.current?.click()}>{label} + {busy?"…":"图片 / Image"}</button>{images.map((image,index)=><span key={index} style={{display:"inline-flex",alignItems:"center",gap:6}}><button type="button" className="icon-btn" style={{width:48,height:48,flexShrink:0}} aria-label={`${label} ${index+1}`} onClick={()=>setPreview(image)}><img src={imagePreviewUrl(image)} alt={`${label} ${index+1}`} style={{width:40,height:40,objectFit:"contain"}}/></button><button type="button" disabled={disabled} aria-label={`删除 / Remove ${label} ${index+1}`} onClick={()=>onChange(images.filter((_,i)=>i!==index))}>×</button></span>)}{error?<p role="alert">{error}</p>:null}{preview?<div role="dialog" aria-label="图片 / Image" className="img-preview-backdrop" onClick={()=>setPreview(undefined)}><img src={imagePreviewUrl(preview)} alt={label} style={{maxWidth:"80vw",maxHeight:"80vh"}}/><button type="button" onClick={()=>setPreview(undefined)}>关闭 / Close</button></div>:null}</div>;
}
