/**
 * StudioAgentHubService - presentation-neutral agent roster and control
 * service for the Studio Agent Hub (05_AGENT_HUB_AND_JOBS.md, WP-050..WP-053).
 *
 * Native semantics arrive exclusively through narrow injected ports:
 *   - roster/status .......... AgentRegistry (get/list/onChange)
 *   - lifecycle .............. AgentLifecycleManager (ensureLive/release/has)
 *   - unread counts .......... IrcBus (unreadCount)
 *   - spawn .................. the TaskTool structured-subagent path
 *   - transcript ............. the native incremental transcript reader
 *
 * The service never exposes session files, transcript paths, worktrees, or
 * native error messages. Generations are derived from native port events and
 * lifecycle outcomes (never from renderer input); transcript cursors are
 * opaque, signed tokens generated by this service instance.
 */

import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import type { AgentKind, AgentRef, RegistryEvent } from "../../registry/agent-registry";

const MAX_MESSAGE_TEXT = 64 * 1024;
const MAX_ID_LENGTH = 512;
const MAX_DEFINITION_LENGTH = 256;
const DEFAULT_LIST_LIMIT = 200;
const MAX_LIST_LIMIT = 500;
const DEFAULT_TRANSCRIPT_PAGE = 50;
const MAX_TRANSCRIPT_PAGE = 100;
const DEFAULT_TRANSCRIPT_MESSAGE_TEXT = 64 * 1024;
const CURSOR_VERSION = "1";
const MAX_HIERARCHY_HOPS = 64;
const TELEMETRY_EMIT_DEBOUNCE_MS = 250;

export type StudioAgentStatus =
	| "starting"
	| "running"
	| "idle"
	| "parked"
	| "reviving"
	| "aborted"
	| "failed"
	| "released";

export type StudioAgentSendMode = "prompt" | "steer" | "followUp";

export type StudioAgentDeliveryOutcome = "injected" | "queued" | "woken" | "revived";

/** Cumulative per-agent usage totals; shape-compatible with AgentMetricsSummary. */
export interface StudioAgentUsage {
	tokens: number;
	requests: number;
	tools: number;
	cost: number;
	durationMs: number;
	durationKind?: string;
	contextTokens?: number;
	contextWindow?: number;
}

export interface StudioAgentSnapshot {
	agentId: string;
	generation: number;
	parentAgentId?: string;
	kind: AgentKind;
	displayName: string;
	status: StudioAgentStatus;
	assignment?: string;
	summary?: string;
	startedAt?: string;
	updatedAt: string;
	hasLiveSession: boolean;
	hasTranscript: boolean;
	unreadCount: number;
	activeJobIds: string[];
	usage?: StudioAgentUsage;
	modelRole?: string;
	resolvedModel?: string;
	/** True when the reported model was selected by retry fallback routing. */
	modelIsFallback?: boolean;
	readOnly?: boolean;
	outputPath?: string;
	patchPath?: string;
	branchName?: string;
}

/**
 * Live per-agent telemetry source. Structurally compatible with a port that
 * reads the agent's active AgentSession (cumulative usage, current model,
 * latest assistant gist) and surfaces its change events. All accessors must
 * be cheap or cached by the wiring; they run inside every roster projection.
 */
export interface StudioAgentTelemetryPort {
	/** Cumulative usage for the agent's active session; undefined when unavailable. */
	liveUsage(agentId: string): StudioAgentUsage | undefined;
	/** Current resolved model id for the active session; undefined when unknown. */
	liveModel(agentId: string): string | undefined;
	/** Short gist of the latest assistant output; undefined when unavailable. */
	liveSummary(agentId: string): string | undefined;
	/**
	 * Re-resolve the agent's current session attachment (e.g. after revive
	 * swapped the AgentSession). Cheap no-op when the session is unchanged.
	 */
	refresh(agentId: string): void;
	/**
	 * Best-effort change stream for the agent's live telemetry. The wiring
	 * keeps the newest session attached; resolving the same agent again must
	 * be a cheap no-op. Returns a no-op unsubscribe when no session is live.
	 */
	onChange(agentId: string, listener: () => void): () => void;
}

export interface StudioMessage {
	id: string;
	role: "user" | "assistant" | "custom" | "system";
	ts: number;
	text: string;
}

export interface StudioAgentTranscriptPage {
	agentId: string;
	generation: number;
	cursor: string;
	nextCursor?: string;
	messages: StudioMessage[];
	eof: boolean;
}

/**
 * Live agent delivery surface. Structurally compatible with the native
 * AgentSession (prompt/steer/followUp/abort/isStreaming).
 */
export interface StudioLiveAgentPort {
	readonly isStreaming: boolean;
	prompt(text: string, options?: { images?: readonly unknown[] }): Promise<boolean>;
	steer(text: string, images?: readonly unknown[]): Promise<void>;
	followUp(text: string, images?: readonly unknown[]): Promise<void>;
	abort(options?: { reason?: string }): Promise<void>;
}

/**
 * Roster port. Structurally compatible with the native AgentRegistry; the
 * live session is read from `AgentRef.session` and narrowed to the
 * StudioLiveAgentPort surface by the service.
 */
export interface StudioAgentRegistryPort {
	get(id: string): AgentRef | undefined;
	list(): AgentRef[];
	onChange(listener: (event: RegistryEvent) => void): () => void;
}

/**
 * Lifecycle port. Structurally compatible with the native
 * AgentLifecycleManager; `release` carries the exact registry ref as the
 * expected generation so the native CAS still guards the mutation.
 */
export interface StudioAgentLifecyclePort {
	ensureLive(id: string): Promise<unknown>;
	release(id: string, expected?: AgentRef, options?: { tombstone?: boolean }): Promise<boolean>;
	has(id: string, expected?: AgentRef): boolean;
}

/** Unread mailbox counts; structurally compatible with IrcBus.unreadCount. */
export interface StudioIrcBusPort {
	unreadCount(agentId: string): number;
}

export interface StudioAgentSpawnRequest {
	definition: string;
	assignment: string;
	context?: string;
	async?: boolean;
	isolation?: string;
	effort?: string;
	callerAgentId?: string;
}

export interface StudioAgentSpawnReceipt {
	agentId: string;
	jobId?: string;
}

/**
 * Spawn port. The production wiring must call the same structured-subagent /
 * TaskTool path the native task tool uses (definition resolution, policy,
 * isolation, session creation, registry registration, async job
 * registration) - this service never assembles a subagent itself.
 */
export interface StudioAgentSpawnerPort {
	spawn(request: StudioAgentSpawnRequest): Promise<StudioAgentSpawnReceipt>;
}

/** Raw page from the native incremental transcript reader (offsets are internal). */
export interface StudioTranscriptReaderPort {
	read(args: { agentId: string; offset: number; limit: number }): Promise<{ messages: StudioMessage[]; eof: boolean }>;
}

export type StudioDestructiveAction = { kind: "release"; agentId: string; generation: number; risk: "destructive" };

export type StudioConfirmationGate = (action: StudioDestructiveAction) => boolean | Promise<boolean>;

export type StudioAgentHubErrorCode =
	| "AGENT_NOT_FOUND"
	| "AGENT_STARTING"
	| "AGENT_GENERATION_CONFLICT"
	| "AGENT_TERMINAL"
	| "NOT_OWNER"
	| "READ_ONLY_TARGET"
	| "PROTECTED_TARGET"
	| "NOT_REVIVABLE"
	| "NOT_RELEASABLE"
	| "CONFIRMATION_REQUIRED"
	| "CONFIRMATION_DENIED"
	| "LIFECYCLE_ERROR"
	| "SPAWN_FAILED"
	| "DELIVERY_FAILED"
	| "TRANSCRIPT_UNAVAILABLE"
	| "INVALID_CURSOR"
	| "STALE_CURSOR"
	| "INVALID_ARGUMENT";

export class StudioAgentHubError extends Error {
	constructor(
		readonly code: StudioAgentHubErrorCode,
		message: string,
		readonly snapshot?: StudioAgentSnapshot,
		readonly action?: StudioDestructiveAction,
	) {
		super(message);
		this.name = "StudioAgentHubError";
	}
}

export interface StudioAgentHubServiceOptions {
	confirmationGate?: StudioConfirmationGate;
	/** Active job ids for an agent; production wiring reads AsyncJobManager rows. */
	activeJobIdsFor?: (agentId: string) => string[];
	/** Live usage/model/summary source; production wiring reads AgentSession. */
	telemetry?: StudioAgentTelemetryPort;
	maxListLimit?: number;
	maxTranscriptPage?: number;
	transcriptMessageLimit?: number;
}

interface StudioTerminalRecord {
	agentId: string;
	displayName: string;
	kind: AgentKind;
	parentAgentId?: string;
	status: "aborted" | "released";
	generation: number;
	startedAt?: string;
	updatedAt: string;
	hasTranscript: boolean;
	usage?: StudioAgentUsage;
	modelRole?: string;
	resolvedModel?: string;
	modelIsFallback?: boolean;
	readOnly?: boolean;
	outputPath?: string;
	patchPath?: string;
	branchName?: string;
}

interface StudioPendingSpawn {
	displayName: string;
	parentAgentId?: string;
}

type StudioEntry =
	| { kind: "live"; ref: AgentRef; snapshot: StudioAgentSnapshot }
	| { kind: "pending"; pending: StudioPendingSpawn; snapshot: StudioAgentSnapshot }
	| { kind: "terminal"; terminal: StudioTerminalRecord; snapshot: StudioAgentSnapshot };

function clampInt(value: number, min: number, max: number): number {
	if (!Number.isSafeInteger(value)) return min;
	return Math.min(max, Math.max(min, value));
}

export class StudioAgentHubService {
	readonly #registry: StudioAgentRegistryPort;
	readonly #lifecycle: StudioAgentLifecyclePort;
	readonly #irc: StudioIrcBusPort;
	readonly #spawner: StudioAgentSpawnerPort;
	readonly #transcript: StudioTranscriptReaderPort;
	readonly #activeJobIdsFor: (agentId: string) => string[];
	readonly #confirmationGate?: StudioConfirmationGate;
	readonly #telemetry?: StudioAgentTelemetryPort;
	readonly #maxListLimit: number;
	readonly #maxTranscriptPage: number;
	readonly #transcriptMessageLimit: number;
	readonly #cursorSecret: Buffer;
	readonly #generations = new Map<string, number>();
	readonly #terminals = new Map<string, StudioTerminalRecord>();
	readonly #pendingSpawns = new Map<string, StudioPendingSpawn>();
	readonly #reviving = new Set<string>();
	readonly #listeners = new Set<(snapshot: StudioAgentSnapshot) => void>();
	readonly #telemetrySubs = new Map<string, () => void>();
	readonly #telemetryTimers = new Map<string, ReturnType<typeof setTimeout>>();
	#unsubscribeRegistry?: () => void;
	#disposed = false;

	constructor(
		registry: StudioAgentRegistryPort,
		lifecycle: StudioAgentLifecyclePort,
		irc: StudioIrcBusPort,
		spawner: StudioAgentSpawnerPort,
		transcript: StudioTranscriptReaderPort,
		options: StudioAgentHubServiceOptions = {},
	) {
		this.#registry = registry;
		this.#lifecycle = lifecycle;
		this.#irc = irc;
		this.#spawner = spawner;
		this.#transcript = transcript;
		this.#activeJobIdsFor = options.activeJobIdsFor ?? (() => []);
		this.#confirmationGate = options.confirmationGate;
		this.#telemetry = options.telemetry;
		this.#maxListLimit = clampInt(options.maxListLimit ?? DEFAULT_LIST_LIMIT, 1, MAX_LIST_LIMIT);
		this.#maxTranscriptPage = clampInt(options.maxTranscriptPage ?? MAX_TRANSCRIPT_PAGE, 1, MAX_TRANSCRIPT_PAGE);
		this.#transcriptMessageLimit =
			options.transcriptMessageLimit === undefined
				? DEFAULT_TRANSCRIPT_MESSAGE_TEXT
				: clampInt(options.transcriptMessageLimit, 1, 1024 * 1024);
		this.#cursorSecret = randomBytes(32);
		this.#unsubscribeRegistry = registry.onChange(event => this.#onRegistryEvent(event));
	}

	/** Roster change notification; snapshots are bounded DTOs. */
	onChange(listener: (snapshot: StudioAgentSnapshot) => void): () => void {
		this.#listeners.add(listener);
		return () => this.#listeners.delete(listener);
	}

	dispose(): void {
		if (this.#disposed) return;
		this.#disposed = true;
		for (const timer of this.#telemetryTimers.values()) clearTimeout(timer);
		this.#telemetryTimers.clear();
		for (const unsubscribe of this.#telemetrySubs.values()) unsubscribe();
		this.#telemetrySubs.clear();
		this.#unsubscribeRegistry?.();
		this.#listeners.clear();
	}

	/**
	 * Bounded roster DTOs. Default: live registry refs (running/idle/parked)
	 * plus pending starts. `includePersisted` adds aborted refs and terminal
	 * records that keep a readable transcript; `includeTerminal` adds every
	 * aborted ref and terminal record.
	 */
	list(
		options: { includeTerminal?: boolean; includePersisted?: boolean; limit?: number } = {},
	): StudioAgentSnapshot[] {
		const limit = clampInt(options.limit ?? DEFAULT_LIST_LIMIT, 1, this.#maxListLimit);
		const includeTerminal = options.includeTerminal === true;
		const includePersisted = options.includePersisted === true;
		const snapshots: StudioAgentSnapshot[] = [];
		for (const ref of this.#registry.list()) {
			if (ref.status === "aborted" && !includeTerminal && !includePersisted) continue;
			this.#ensureGeneration(ref.id);
			this.#pendingSpawns.delete(ref.id);
			snapshots.push(this.#liveSnapshot(ref.id, ref));
		}
		for (const [agentId, pending] of this.#pendingSpawns) {
			if (!this.#registry.get(agentId)) snapshots.push(this.#pendingSnapshot(agentId, pending));
		}
		for (const terminal of this.#terminals.values()) {
			if (this.#registry.get(terminal.agentId)) continue;
			if (includeTerminal || (includePersisted && terminal.hasTranscript)) {
				snapshots.push(this.#terminalSnapshot(terminal));
			}
		}
		snapshots.sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : a.updatedAt > b.updatedAt ? -1 : 0));
		return snapshots.slice(0, limit);
	}

	get(agentId: string): StudioAgentSnapshot {
		this.#validateId(agentId);
		const entry = this.#resolveEntry(agentId);
		if (!entry) throw new StudioAgentHubError("AGENT_NOT_FOUND", `Agent "${agentId}" was not found`);
		return structuredClone(entry.snapshot);
	}

	async send(args: {
		agentId: string;
		expectedGeneration: number;
		text: string;
		mode: StudioAgentSendMode;
		callerAgentId: string;
		images?: readonly unknown[];
	}): Promise<{
		outcome: StudioAgentDeliveryOutcome;
		generation: number;
		snapshot: StudioAgentSnapshot;
	}> {
		this.#validateId(args.agentId);
		this.#validateGeneration(args.expectedGeneration);
		const text = args.text.trim();
		if (text.length === 0 || text.length > MAX_MESSAGE_TEXT) {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Message text must be between 1 and 64 KiB");
		}
		if (args.mode !== "prompt" && args.mode !== "steer" && args.mode !== "followUp") {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Delivery mode must be prompt, steer, or followUp");
		}
		const entry = this.#resolveEntry(args.agentId);
		if (!entry) throw new StudioAgentHubError("AGENT_NOT_FOUND", `Agent "${args.agentId}" was not found`);
		if (entry.kind === "terminal") {
			throw new StudioAgentHubError("AGENT_TERMINAL", `Agent "${args.agentId}" is terminal`, entry.snapshot);
		}
		if (entry.kind === "pending") {
			throw new StudioAgentHubError("AGENT_STARTING", `Agent "${args.agentId}" is still starting`);
		}
		const ref = entry.ref;
		if (entry.snapshot.generation !== args.expectedGeneration) {
			throw new StudioAgentHubError(
				"AGENT_GENERATION_CONFLICT",
				`Agent "${args.agentId}" changed; refresh before messaging`,
				entry.snapshot,
			);
		}
		if (ref.kind === "advisor") {
			throw new StudioAgentHubError("READ_ONLY_TARGET", `Agent "${args.agentId}" is a read-only advisor`);
		}
		if (ref.status === "aborted") {
			throw new StudioAgentHubError("AGENT_TERMINAL", `Agent "${args.agentId}" is terminal`, entry.snapshot);
		}
		this.#assertScope(args.callerAgentId, args.agentId, entry);

		let revived = false;
		let live = this.#livePort(ref);
		if (!live && ref.status === "parked") {
			live = await this.#revive(args.agentId, ref);
			revived = true;
		}
		if (!live) {
			throw new StudioAgentHubError("LIFECYCLE_ERROR", `Agent "${args.agentId}" has no live session`);
		}
		const wasStreaming = live.isStreaming;
		const images = args.images;
		try {
			if (args.mode === "prompt") {
				const submitted = images === undefined ? await live.prompt(text) : await live.prompt(text, { images });
				if (submitted === false) {
					throw new StudioAgentHubError("DELIVERY_FAILED", `Message to "${args.agentId}" was not accepted`);
				}
			} else if (args.mode === "steer") {
				if (images === undefined) await live.steer(text);
				else await live.steer(text, images);
			} else if (images === undefined) {
				await live.followUp(text);
			} else {
				await live.followUp(text, images);
			}
		} catch (error) {
			if (error instanceof StudioAgentHubError) throw error;
			throw new StudioAgentHubError("DELIVERY_FAILED", `Message to "${args.agentId}" could not be delivered`);
		}
		const outcome: StudioAgentDeliveryOutcome = revived
			? "revived"
			: args.mode === "prompt"
				? wasStreaming
					? "queued"
					: "woken"
				: args.mode === "steer"
					? wasStreaming
						? "injected"
						: "queued"
					: "queued";
		const current = this.#resolveEntry(args.agentId);
		const snapshot = current?.snapshot ?? this.#fallbackSnapshot(args.agentId);
		return { outcome, generation: snapshot.generation, snapshot };
	}

	async spawn(args: {
		definition: string;
		assignment: string;
		context?: string;
		async?: boolean;
		isolation?: string;
		effort?: string;
		callerAgentId: string;
	}): Promise<{ agentId: string; jobId?: string; status: "starting" }> {
		const definition = args.definition.trim();
		const assignment = args.assignment.trim();
		if (definition.length === 0 || definition.length > MAX_DEFINITION_LENGTH) {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Spawn definition must be between 1 and 256 characters");
		}
		if (assignment.length === 0 || assignment.length > MAX_MESSAGE_TEXT) {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Spawn assignment must be between 1 and 64 KiB");
		}
		if (args.context !== undefined && (args.context.trim().length === 0 || args.context.length > MAX_MESSAGE_TEXT)) {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Spawn context must be at most 64 KiB");
		}
		if (args.isolation !== undefined && args.isolation !== "patch" && args.isolation !== "branch") {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Isolation must be patch or branch");
		}
		if (args.effort !== undefined && args.effort !== "lo" && args.effort !== "med" && args.effort !== "hi") {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Spawn effort must be lo, med, or hi");
		}
		let receipt: StudioAgentSpawnReceipt;
		try {
			receipt = await this.#spawner.spawn({
				definition,
				assignment,
				...(args.context !== undefined ? { context: args.context } : {}),
				...(args.async !== undefined ? { async: args.async } : {}),
				...(args.isolation !== undefined ? { isolation: args.isolation } : {}),
				...(args.effort !== undefined ? { effort: args.effort } : {}),
				callerAgentId: args.callerAgentId,
			});
		} catch {
			throw new StudioAgentHubError("SPAWN_FAILED", "Agent spawn failed; see the runtime log for details");
		}
		this.#validateId(receipt.agentId);
		this.#pendingSpawns.set(receipt.agentId, {
			displayName: receipt.agentId,
			parentAgentId: args.callerAgentId,
		});
		this.#ensureGeneration(receipt.agentId);
		this.#emit(receipt.agentId);
		return {
			agentId: receipt.agentId,
			...(receipt.jobId !== undefined ? { jobId: receipt.jobId } : {}),
			status: "starting",
		};
	}

	async kill(args: {
		agentId: string;
		expectedGeneration: number;
		callerAgentId: string;
	}): Promise<{ killed: true; snapshot: StudioAgentSnapshot }> {
		this.#validateId(args.agentId);
		this.#validateGeneration(args.expectedGeneration);
		const entry = this.#requireLiveEntry(args.agentId, "kill");
		const ref = entry.ref;
		if (entry.snapshot.generation !== args.expectedGeneration) {
			throw new StudioAgentHubError(
				"AGENT_GENERATION_CONFLICT",
				`Agent "${args.agentId}" changed; refresh before killing`,
				entry.snapshot,
			);
		}
		if (ref.kind === "advisor") {
			throw new StudioAgentHubError("READ_ONLY_TARGET", `Agent "${args.agentId}" is a read-only advisor`);
		}
		if (ref.kind === "main") {
			throw new StudioAgentHubError("PROTECTED_TARGET", `Agent "${args.agentId}" cannot be killed`);
		}
		if (ref.status === "aborted") {
			throw new StudioAgentHubError("AGENT_TERMINAL", `Agent "${args.agentId}" is terminal`, entry.snapshot);
		}
		this.#assertScope(args.callerAgentId, args.agentId, entry);
		// Studio confirms kill in the Agent Hub dialog. Do not emit a second
		// InteractionDeck gate — the command should settle immediately.
		const live = this.#livePort(ref);
		if (live && ref.status === "running") {
			try {
				await live.abort({ reason: "killed from Studio agent hub" });
			} catch {
				throw new StudioAgentHubError("LIFECYCLE_ERROR", `Agent "${args.agentId}" could not be aborted`);
			}
		}
		let released = false;
		try {
			released = await this.#lifecycle.release(args.agentId, ref, { tombstone: true });
		} catch {
			throw new StudioAgentHubError("LIFECYCLE_ERROR", `Agent "${args.agentId}" could not be settled`);
		}
		if (!released) {
			throw new StudioAgentHubError(
				"AGENT_GENERATION_CONFLICT",
				`Agent "${args.agentId}" changed before the kill could settle`,
				this.#resolveEntry(args.agentId)?.snapshot,
			);
		}
		this.#terminals.set(args.agentId, this.#terminalRecord(ref, "aborted", entry.snapshot.generation));
		this.#emit(args.agentId);
		const snapshot = this.#resolveEntry(args.agentId)?.snapshot ?? this.#fallbackSnapshot(args.agentId);
		return { killed: true, snapshot };
	}

	async revive(args: {
		agentId: string;
		expectedGeneration: number;
		callerAgentId: string;
	}): Promise<{ revived: true; generation: number; snapshot: StudioAgentSnapshot }> {
		this.#validateId(args.agentId);
		this.#validateGeneration(args.expectedGeneration);
		const entry = this.#requireLiveEntry(args.agentId, "revive");
		const ref = entry.ref;
		if (entry.snapshot.generation !== args.expectedGeneration) {
			throw new StudioAgentHubError(
				"AGENT_GENERATION_CONFLICT",
				`Agent "${args.agentId}" changed; refresh before reviving`,
				entry.snapshot,
			);
		}
		if (ref.kind === "advisor") {
			throw new StudioAgentHubError("READ_ONLY_TARGET", `Agent "${args.agentId}" is a read-only advisor`);
		}
		this.#assertScope(args.callerAgentId, args.agentId, entry);
		await this.#revive(args.agentId, ref);
		const snapshot = this.#resolveEntry(args.agentId)?.snapshot ?? this.#fallbackSnapshot(args.agentId);
		return { revived: true, generation: snapshot.generation, snapshot };
	}

	async release(args: {
		agentId: string;
		expectedGeneration: number;
		callerAgentId: string;
	}): Promise<{ released: true; snapshot?: StudioAgentSnapshot; gone: boolean }> {
		this.#validateId(args.agentId);
		this.#validateGeneration(args.expectedGeneration);
		const entry = this.#resolveEntry(args.agentId);
		if (!entry) throw new StudioAgentHubError("AGENT_NOT_FOUND", `Agent "${args.agentId}" was not found`);
		if (entry.kind === "pending") {
			throw new StudioAgentHubError("AGENT_STARTING", `Agent "${args.agentId}" is still starting`);
		}
		if (entry.snapshot.generation !== args.expectedGeneration) {
			throw new StudioAgentHubError(
				"AGENT_GENERATION_CONFLICT",
				`Agent "${args.agentId}" changed; refresh before releasing`,
				entry.snapshot,
			);
		}
		if (entry.kind === "terminal") {
			if (entry.terminal.kind === "advisor") {
				throw new StudioAgentHubError("READ_ONLY_TARGET", `Agent "${args.agentId}" is a read-only advisor`);
			}
			this.#assertScope(args.callerAgentId, args.agentId, entry);
			await this.#requireConfirmation({
				kind: "release",
				agentId: args.agentId,
				generation: entry.snapshot.generation,
				risk: "destructive",
			});
			const nativeRef = this.#registry.get(args.agentId);
			if (nativeRef !== undefined) {
				let removed = false;
				try {
					removed = await this.#lifecycle.release(args.agentId, nativeRef);
				} catch {
					throw new StudioAgentHubError("LIFECYCLE_ERROR", `Agent "${args.agentId}" could not be released`);
				}
				if (!removed) {
					throw new StudioAgentHubError(
						"AGENT_GENERATION_CONFLICT",
						`Agent "${args.agentId}" changed before the release could settle`,
						entry.snapshot,
					);
				}
			}
			this.#terminals.delete(args.agentId);
			this.#emit(args.agentId);
			return { released: true, gone: true };
		}
		const ref = entry.ref;
		if (ref.kind === "advisor") {
			throw new StudioAgentHubError("READ_ONLY_TARGET", `Agent "${args.agentId}" is a read-only advisor`);
		}
		if (ref.status === "running" || ref.status === "idle") {
			throw new StudioAgentHubError(
				"NOT_RELEASABLE",
				`Agent "${args.agentId}" is ${ref.status}; kill it before release`,
				entry.snapshot,
			);
		}
		this.#assertScope(args.callerAgentId, args.agentId, entry);
		await this.#requireConfirmation({
			kind: "release",
			agentId: args.agentId,
			generation: entry.snapshot.generation,
			risk: "destructive",
		});
		let released = false;
		try {
			released = await this.#lifecycle.release(args.agentId, ref);
		} catch {
			throw new StudioAgentHubError("LIFECYCLE_ERROR", `Agent "${args.agentId}" could not be released`);
		}
		if (!released) {
			throw new StudioAgentHubError(
				"AGENT_GENERATION_CONFLICT",
				`Agent "${args.agentId}" changed before the release could settle`,
				this.#resolveEntry(args.agentId)?.snapshot,
			);
		}
		this.#terminals.set(args.agentId, this.#terminalRecord(ref, "released", entry.snapshot.generation));
		this.#emit(args.agentId);
		return {
			released: true,
			gone: false,
			snapshot: this.#terminalSnapshot(this.#terminals.get(args.agentId) as StudioTerminalRecord),
		};
	}

	async readTranscript(args: {
		agentId: string;
		cursor?: string;
		limit?: number;
	}): Promise<StudioAgentTranscriptPage> {
		this.#validateId(args.agentId);
		const entry = this.#resolveEntry(args.agentId);
		if (!entry) throw new StudioAgentHubError("AGENT_NOT_FOUND", `Agent "${args.agentId}" was not found`);
		if (!entry.snapshot.hasTranscript) {
			throw new StudioAgentHubError("TRANSCRIPT_UNAVAILABLE", `Agent "${args.agentId}" has no transcript`);
		}
		const generation = entry.snapshot.generation;
		const limit =
			args.limit === undefined ? DEFAULT_TRANSCRIPT_PAGE : clampInt(args.limit, 1, this.#maxTranscriptPage);
		const offset = args.cursor === undefined ? 0 : this.#decodeCursor(args.cursor, generation);
		let page: { messages: StudioMessage[]; eof: boolean };
		try {
			page = await this.#transcript.read({ agentId: args.agentId, offset, limit });
		} catch {
			throw new StudioAgentHubError("TRANSCRIPT_UNAVAILABLE", "Transcript could not be read");
		}
		const raw = page.messages.slice(0, limit);
		const messages = raw
			.map(message => ({
				id: message.id,
				role: message.role,
				ts: message.ts,
				text:
					message.text.length > this.#transcriptMessageLimit
						? message.text.slice(0, this.#transcriptMessageLimit)
						: message.text,
			}))
			.filter(message => message.text.length > 0);
		const eof = page.eof || raw.length < limit;
		const nextOffset = offset + raw.length;
		return {
			agentId: args.agentId,
			generation,
			cursor: this.#encodeCursor(generation, offset),
			...(nextOffset > offset && !eof ? { nextCursor: this.#encodeCursor(generation, nextOffset) } : {}),
			messages,
			eof,
		};
	}

	#requireLiveEntry(agentId: string, _operation: string): Extract<StudioEntry, { kind: "live" }> {
		const entry = this.#resolveEntry(agentId);
		if (!entry) throw new StudioAgentHubError("AGENT_NOT_FOUND", `Agent "${agentId}" was not found`);
		if (entry.kind === "terminal") {
			throw new StudioAgentHubError("AGENT_TERMINAL", `Agent "${agentId}" is terminal`, entry.snapshot);
		}
		if (entry.kind === "pending") {
			throw new StudioAgentHubError("AGENT_STARTING", `Agent "${agentId}" is still starting`);
		}
		return entry;
	}

	#resolveEntry(agentId: string): StudioEntry | undefined {
		const ref = this.#registry.get(agentId);
		const terminal = this.#terminals.get(agentId);
		if (terminal && (ref === undefined || ref.status === "aborted")) {
			return { kind: "terminal", terminal, snapshot: this.#terminalSnapshot(terminal) };
		}
		if (ref) {
			this.#ensureGeneration(agentId);
			this.#pendingSpawns.delete(agentId);
			return { kind: "live", ref, snapshot: this.#liveSnapshot(agentId, ref) };
		}
		const pending = this.#pendingSpawns.get(agentId);
		if (pending) {
			this.#ensureGeneration(agentId);
			return { kind: "pending", pending, snapshot: this.#pendingSnapshot(agentId, pending) };
		}
		if (terminal) return { kind: "terminal", terminal, snapshot: this.#terminalSnapshot(terminal) };
		return undefined;
	}

	#liveSnapshot(agentId: string, ref: AgentRef): StudioAgentSnapshot {
		this.#syncTelemetry(agentId, ref);
		const history = ref.history;
		const liveUsage = this.#telemetry?.liveUsage(agentId);
		const usage = liveUsage ?? history?.metrics;
		const liveModel = this.#telemetry?.liveModel(agentId);
		const resolvedModel = liveModel ?? history?.resolvedModel;
		const summary = ref.activity === undefined ? this.#telemetry?.liveSummary(agentId) : undefined;
		return {
			agentId,
			generation: this.#generations.get(agentId) ?? 1,
			...(ref.parentId !== undefined ? { parentAgentId: ref.parentId } : {}),
			kind: ref.kind,
			displayName: ref.displayName,
			status: this.#reviving.has(agentId) ? "reviving" : mapNativeStatus(ref.status),
			...(ref.activity !== undefined ? { assignment: ref.activity } : {}),
			...(summary !== undefined && summary.length > 0 ? { summary } : {}),
			startedAt: new Date(ref.createdAt).toISOString(),
			updatedAt: new Date(ref.lastActivity).toISOString(),
			hasLiveSession: ref.session !== null,
			hasTranscript: ref.session !== null || ref.sessionFile !== null,
			unreadCount: this.#irc.unreadCount(agentId),
			activeJobIds: this.#activeJobIdsFor(agentId),
			...(usage !== undefined ? { usage: { ...usage } } : {}),
			...(history?.modelRole !== undefined ? { modelRole: history.modelRole } : {}),
			...(resolvedModel !== undefined && resolvedModel.length > 0 ? { resolvedModel } : {}),
			// The fallback marker describes the persisted resolution; a live
			// session's current model is authoritative and has no marker.
			...(liveModel === undefined && history?.resolvedModelIsFallback === true ? { modelIsFallback: true } : {}),
			...(history?.readOnly !== undefined ? { readOnly: history.readOnly } : {}),
			...(history?.outputPath !== undefined ? { outputPath: history.outputPath } : {}),
			...(history?.patchPath !== undefined ? { patchPath: history.patchPath } : {}),
			...(history?.branchName !== undefined ? { branchName: history.branchName } : {}),
		};
	}

	#pendingSnapshot(agentId: string, pending: StudioPendingSpawn): StudioAgentSnapshot {
		return {
			agentId,
			generation: this.#generations.get(agentId) ?? 1,
			...(pending.parentAgentId !== undefined ? { parentAgentId: pending.parentAgentId } : {}),
			kind: "sub",
			displayName: pending.displayName,
			status: "starting",
			updatedAt: new Date().toISOString(),
			hasLiveSession: false,
			hasTranscript: false,
			unreadCount: 0,
			activeJobIds: [],
		};
	}

	#terminalSnapshot(terminal: StudioTerminalRecord): StudioAgentSnapshot {
		return {
			agentId: terminal.agentId,
			generation: terminal.generation,
			...(terminal.parentAgentId !== undefined ? { parentAgentId: terminal.parentAgentId } : {}),
			kind: terminal.kind,
			displayName: terminal.displayName,
			status: terminal.status,
			...(terminal.startedAt !== undefined ? { startedAt: terminal.startedAt } : {}),
			updatedAt: terminal.updatedAt,
			hasLiveSession: false,
			hasTranscript: terminal.hasTranscript,
			unreadCount: 0,
			activeJobIds: [],
			...(terminal.usage !== undefined ? { usage: { ...terminal.usage } } : {}),
			...(terminal.modelRole !== undefined ? { modelRole: terminal.modelRole } : {}),
			...(terminal.resolvedModel !== undefined ? { resolvedModel: terminal.resolvedModel } : {}),
			...(terminal.modelIsFallback === true ? { modelIsFallback: true } : {}),
			...(terminal.readOnly !== undefined ? { readOnly: terminal.readOnly } : {}),
			...(terminal.outputPath !== undefined ? { outputPath: terminal.outputPath } : {}),
			...(terminal.patchPath !== undefined ? { patchPath: terminal.patchPath } : {}),
			...(terminal.branchName !== undefined ? { branchName: terminal.branchName } : {}),
		};
	}

	#terminalRecord(ref: AgentRef, status: "aborted" | "released", generation: number): StudioTerminalRecord {
		const history = ref.history;
		return {
			agentId: ref.id,
			displayName: ref.displayName,
			kind: ref.kind,
			...(ref.parentId !== undefined ? { parentAgentId: ref.parentId } : {}),
			status,
			generation,
			startedAt: new Date(ref.createdAt).toISOString(),
			updatedAt: new Date().toISOString(),
			hasTranscript: ref.session !== null || ref.sessionFile !== null,
			...(history?.metrics !== undefined ? { usage: { ...history.metrics } } : {}),
			...(history?.modelRole !== undefined ? { modelRole: history.modelRole } : {}),
			...(history?.resolvedModel !== undefined ? { resolvedModel: history.resolvedModel } : {}),
			...(history?.resolvedModelIsFallback === true ? { modelIsFallback: true } : {}),
			...(history?.readOnly !== undefined ? { readOnly: history.readOnly } : {}),
			...(history?.outputPath !== undefined ? { outputPath: history.outputPath } : {}),
			...(history?.patchPath !== undefined ? { patchPath: history.patchPath } : {}),
			...(history?.branchName !== undefined ? { branchName: history.branchName } : {}),
		};
	}

	#fallbackSnapshot(agentId: string): StudioAgentSnapshot {
		const terminal = this.#terminals.get(agentId);
		if (terminal) return this.#terminalSnapshot(terminal);
		return {
			agentId,
			generation: this.#generations.get(agentId) ?? 1,
			kind: "sub",
			displayName: agentId,
			status: "released",
			updatedAt: new Date().toISOString(),
			hasLiveSession: false,
			hasTranscript: false,
			unreadCount: 0,
			activeJobIds: [],
		};
	}

	async #revive(agentId: string, ref: AgentRef): Promise<StudioLiveAgentPort> {
		if (ref.status !== "parked") {
			throw new StudioAgentHubError(
				"NOT_REVIVABLE",
				`Agent "${agentId}" is ${ref.status}; only parked agents can be revived`,
				this.#liveSnapshot(agentId, ref),
			);
		}
		this.#reviving.add(agentId);
		this.#emit(agentId);
		try {
			await this.#lifecycle.ensureLive(agentId);
		} catch {
			throw new StudioAgentHubError("LIFECYCLE_ERROR", `Agent "${agentId}" could not be revived`);
		} finally {
			this.#reviving.delete(agentId);
		}
		const live = this.#registry.get(agentId)?.session as unknown as StudioLiveAgentPort | null;
		if (!live) {
			throw new StudioAgentHubError("LIFECYCLE_ERROR", `Agent "${agentId}" has no live session after revival`);
		}
		// Revive is an authoritative generation transition driven by the native
		// lifecycle port - never by the renderer's expectedGeneration.
		this.#generations.set(agentId, (this.#generations.get(agentId) ?? 1) + 1);
		this.#emit(agentId);
		return live;
	}

	#livePort(ref: AgentRef): StudioLiveAgentPort | undefined {
		return (ref.session as unknown as StudioLiveAgentPort | null) ?? undefined;
	}

	#assertScope(callerAgentId: string, targetAgentId: string, entry: StudioEntry): void {
		if (callerAgentId === targetAgentId) return;
		const parentAgentId =
			entry.kind === "live"
				? entry.ref.parentId
				: entry.kind === "pending"
					? entry.pending.parentAgentId
					: entry.terminal.parentAgentId;
		if (this.#isAncestor(callerAgentId, parentAgentId)) return;
		throw new StudioAgentHubError("NOT_OWNER", `Agent "${callerAgentId}" cannot control "${targetAgentId}"`);
	}

	#isAncestor(ancestorId: string, descendantId: string | undefined): boolean {
		let current = descendantId;
		let hops = 0;
		while (current !== undefined && hops < MAX_HIERARCHY_HOPS) {
			if (current === ancestorId) return true;
			current = this.#registry.get(current)?.parentId;
			hops += 1;
		}
		return false;
	}

	async #requireConfirmation(action: StudioDestructiveAction): Promise<void> {
		if (!this.#confirmationGate) {
			throw new StudioAgentHubError(
				"CONFIRMATION_REQUIRED",
				`Destructive ${action.kind} requires host confirmation`,
				undefined,
				action,
			);
		}
		const granted = await this.#confirmationGate(action);
		if (!granted) {
			throw new StudioAgentHubError("CONFIRMATION_DENIED", `Destructive ${action.kind} was not confirmed`);
		}
	}

	#onRegistryEvent(event: RegistryEvent): void {
		const { id } = event.ref;
		if (event.type === "registered") {
			const wasPending = this.#pendingSpawns.has(id);
			this.#pendingSpawns.delete(id);
			const current = this.#generations.get(id);
			// Re-registration after release/removal is a new native era: stale
			// page buttons must never re-match by name.
			this.#generations.set(id, current === undefined ? 1 : wasPending ? current : current + 1);
		} else if (event.type === "removed") {
			const current = this.#generations.get(id);
			if (current !== undefined && !this.#terminals.has(id)) {
				this.#terminals.set(id, this.#terminalRecord(event.ref, "released", current));
			}
			this.#telemetrySubs.get(id)?.();
			this.#telemetrySubs.delete(id);
		}
		this.#emit(id);
	}

	/**
	 * Keep exactly one telemetry subscription per agent with a live session.
	 * Idempotent: roster projections call it on every pass, so it must be a
	 * cheap map check once the subscription exists.
	 */
	#syncTelemetry(agentId: string, ref: AgentRef): void {
		if (!this.#telemetry) return;
		this.#telemetry.refresh(agentId);
		if (ref.session === null) {
			const detach = this.#telemetrySubs.get(agentId);
			if (detach !== undefined) {
				detach();
				this.#telemetrySubs.delete(agentId);
			}
			return;
		}
		if (this.#telemetrySubs.has(agentId)) return;
		const unsubscribe = this.#telemetry.onChange(agentId, () => this.#scheduleTelemetryEmit(agentId));
		this.#telemetrySubs.set(agentId, unsubscribe);
	}

	/**
	 * Debounced roster refresh for per-agent usage changes. Session events can
	 * burst per token stream, so coalesce them before re-emitting snapshots.
	 */
	#scheduleTelemetryEmit(agentId: string): void {
		if (this.#disposed) return;
		if (this.#telemetryTimers.has(agentId)) return;
		this.#telemetryTimers.set(
			agentId,
			setTimeout(() => {
				this.#telemetryTimers.delete(agentId);
				if (this.#disposed) return;
				// Re-sync first so a replaced session (e.g. after revive)
				// re-attaches before the snapshot is rebuilt.
				const ref = this.#registry.get(agentId);
				if (ref) this.#syncTelemetry(agentId, ref);
				this.#emit(agentId);
			}, TELEMETRY_EMIT_DEBOUNCE_MS),
		);
	}

	#ensureGeneration(agentId: string): void {
		if (!this.#generations.has(agentId)) this.#generations.set(agentId, 1);
	}

	#emit(agentId: string): void {
		if (this.#listeners.size === 0) return;
		const entry = this.#resolveEntry(agentId);
		if (!entry) return;
		for (const listener of this.#listeners) {
			try {
				listener(structuredClone(entry.snapshot));
			} catch {
				// listeners must not break roster dispatch
			}
		}
	}

	#encodeCursor(generation: number, offset: number): string {
		const payload = [CURSOR_VERSION, String(generation), String(offset)].join(":");
		return Buffer.from(`${payload}:${this.#sign(payload)}`, "utf8").toString("base64url");
	}

	#decodeCursor(cursor: string, generation: number): number {
		if (cursor.length === 0 || cursor.length > 512) {
			throw new StudioAgentHubError("INVALID_CURSOR", "Malformed transcript cursor");
		}
		let payload: string;
		try {
			const decoded = Buffer.from(cursor, "base64url");
			if (decoded.toString("base64url") !== cursor) {
				throw new Error("Non-canonical cursor encoding");
			}
			payload = decoded.toString("utf8");
		} catch {
			throw new StudioAgentHubError("INVALID_CURSOR", "Malformed transcript cursor");
		}
		const parts = payload.split(":");
		if (parts.length !== 4 || parts[0] !== CURSOR_VERSION) {
			throw new StudioAgentHubError("INVALID_CURSOR", "Malformed transcript cursor");
		}
		if (!this.#verify(parts[1], parts[2], parts[3] ?? "")) {
			throw new StudioAgentHubError("INVALID_CURSOR", "Malformed transcript cursor");
		}
		const cursorGeneration = Number(parts[1]);
		const offset = Number(parts[2]);
		if (!Number.isSafeInteger(cursorGeneration) || !Number.isSafeInteger(offset) || offset < 0) {
			throw new StudioAgentHubError("INVALID_CURSOR", "Malformed transcript cursor");
		}
		if (cursorGeneration !== generation) {
			throw new StudioAgentHubError("STALE_CURSOR", "Transcript cursor belongs to an older agent generation");
		}
		return offset;
	}

	#sign(payload: string): string {
		return createHmac("sha256", this.#cursorSecret).update(payload).digest("base64url");
	}

	#verify(generationText: string, offsetText: string, signature: string): boolean {
		const expected = this.#sign([CURSOR_VERSION, generationText, offsetText].join(":"));
		const a = Buffer.from(expected, "base64url");
		const b = Buffer.from(signature, "base64url");
		return a.length === b.length && a.length > 0 && timingSafeEqual(a, b);
	}

	#validateId(agentId: string): void {
		if (typeof agentId !== "string" || agentId.length === 0 || agentId.length > MAX_ID_LENGTH) {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Agent id is invalid");
		}
	}

	#validateGeneration(expectedGeneration: number): void {
		if (!Number.isSafeInteger(expectedGeneration) || expectedGeneration < 1) {
			throw new StudioAgentHubError("INVALID_ARGUMENT", "Expected generation is invalid");
		}
	}
}

function mapNativeStatus(status: AgentRef["status"]): StudioAgentStatus {
	switch (status) {
		case "running":
			return "running";
		case "idle":
			return "idle";
		case "parked":
			return "parked";
		case "aborted":
			return "aborted";
	}
}
