import { useCallback, useEffect, useRef, useState } from "react";
import type { CommandInput, StudioClient } from "@omp-studio/client-contract";
import { validateSkillshareAction, type SkillshareAction, type SkillshareActionState, type SkillshareResultMap, type SkillshareReview } from "@omp-studio/studio-protocol";
import { useI18n } from "../i18n";
import { usePreviewMode } from "../preview/PreviewContext";
import { hostErrorMessage, waitReceipt } from "../hostError";
import { PREVIEW_SKILLSHARE_INSTALLED, PREVIEW_SKILLSHARE_PACKAGE, PREVIEW_SKILLSHARE_SEARCH, PREVIEW_SKILLSHARE_STATUS, PREVIEW_SKILLSHARE_TOKENS } from "../preview/skillsharePreview";
import "./skillshare.css";

export function SkillsharePane({ client, sessionId, available }: { client: StudioClient; sessionId?: string | undefined; available: boolean }) {
  const { preview } = usePreviewMode(); const { resolvedLanguage } = useI18n(); const zh = resolvedLanguage === "zh"; const t = (cn: string, en: string) => zh ? cn : en;
  const [tab, setTab] = useState<"browse" | "installed" | "manage" | "tokens">("browse");
  const [status, setStatus] = useState<SkillshareResultMap["skillshare.status"]>(); const [search, setSearch] = useState<SkillshareResultMap["skillshare.search"]>(); const [detail, setDetail] = useState<SkillshareResultMap["skillshare.package"]>(); const [installed, setInstalled] = useState<SkillshareResultMap["skillshare.installed"]>(); const [tokens, setTokens] = useState<SkillshareResultMap["skillshare.tokens"]>();
  const [query, setQuery] = useState(""); const [sort, setSort] = useState<"relevance" | "downloads" | "recent">("relevance"); const [scope, setScope] = useState<"project" | "user">("project"); const [specs, setSpecs] = useState(""); const [packageName, setPackageName] = useState("");
  const [actionType, setActionType] = useState<SkillshareAction["type"]>("publish"); const [directory, setDirectory] = useState("."); const [publishScope, setPublishScope] = useState(""); const [tag, setTag] = useState("latest"); const [version, setVersion] = useState(""); const [bump, setBump] = useState("patch"); const [username, setUsername] = useState(""); const [message, setMessage] = useState(""); const [yanked, setYanked] = useState(true); const [tokenName, setTokenName] = useState(""); const [tokenPackages, setTokenPackages] = useState(""); const [expiry, setExpiry] = useState("");
  const [review, setReview] = useState<SkillshareReview>(); const [allowScripts, setAllowScripts] = useState(false); const [allowSecrets, setAllowSecrets] = useState(false); const [action, setAction] = useState<SkillshareActionState>(); const [secret, setSecret] = useState<{ token: string; name: string }>();
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const epoch = useRef(0); const lock = useRef(false); const confirm = useRef<HTMLButtonElement>(null); const enabled = preview || (available && !!sessionId);
  const invoke = useCallback(async <K extends keyof SkillshareResultMap>(kind: K, input: CommandInput<K>): Promise<SkillshareResultMap[K]> => {
    const handle = await client.command(kind, input); return (await waitReceipt<{ result: SkillshareResultMap[K] }>(client, handle.requestId, 90000)).result;
  }, [client]);
  const run = async (fn: (generation: number) => Promise<void>) => { if (lock.current) return; const generation = epoch.current; lock.current = true; setBusy(true); setError(""); try { await fn(generation); } catch (cause) { if (generation === epoch.current) setError(hostErrorMessage(cause, "Skillshare request failed")); } finally { if (generation === epoch.current) { lock.current = false; setBusy(false); } } };
  const load = useCallback(async () => {
    const generation = epoch.current;
    if (preview) { setStatus(PREVIEW_SKILLSHARE_STATUS); setSearch(PREVIEW_SKILLSHARE_SEARCH); setInstalled(PREVIEW_SKILLSHARE_INSTALLED); setTokens(PREVIEW_SKILLSHARE_TOKENS); return; }
    if (!available || !sessionId) return;
    const [state, inventory] = await Promise.all([invoke("skillshare.status", { sessionId }), invoke("skillshare.installed", { sessionId })]);
    if (generation === epoch.current) { setStatus(state); setInstalled(inventory); }
  }, [preview, available, sessionId, invoke]);
  useEffect(() => { const generation = ++epoch.current; lock.current = false; setBusy(false); setStatus(undefined); setSearch(undefined); setDetail(undefined); setInstalled(undefined); setTokens(undefined); setReview(undefined); setAction(undefined); setSecret(undefined); setError(""); void load().catch(cause => { if (generation === epoch.current) setError(hostErrorMessage(cause, "Registry unavailable")); }); return () => { epoch.current++; }; }, [load]);
  useEffect(() => { const hide = () => { if (document.hidden) setSecret(undefined); }; document.addEventListener("visibilitychange", hide); return () => document.removeEventListener("visibilitychange", hide); }, []);
  useEffect(() => { setSecret(undefined); }, [tab]);
  useEffect(() => { if (review) { setAllowScripts(false); setAllowSecrets(false); confirm.current?.focus(); } }, [review]);
  useEffect(() => {
    if (preview || !sessionId || !action || action.state !== "running") return;
    let alive = true; let timer: ReturnType<typeof setTimeout>;
    const poll = async () => { try { const value = await invoke("skillshare.action", { sessionId, id: action.id }); if (!alive) return; setAction(value.action); if (value.action.state === "running") timer = setTimeout(() => void poll(), 1500); else await load(); } catch (cause) { if (alive) setError(hostErrorMessage(cause, "Action result is unknown; inspect the registry before submitting again")); } };
    void poll(); return () => { alive = false; clearTimeout(timer); };
  }, [action?.id, action?.state, preview, sessionId, invoke, load]);
  const prepare = (request: SkillshareAction) => void run(async generation => {
    validateSkillshareAction(request); setSecret(undefined);
    if (preview) {
      const id = crypto.randomUUID(); const scripts = ["install", "publish", "update"].includes(request.type) ? ["scripts/check.sh"] : [];
      setReview({ id, digest: "0".repeat(64), expiresAt: Date.now() + 600000, action: request, registry: PREVIEW_SKILLSHARE_STATUS.registry, remoteWrite: !["install", "update", "uninstall", "version", "reload"].includes(request.type), changes: "package" in request ? [{ package: request.package, to: "1.2.0" }] : [], files: request.type === "publish" ? PREVIEW_SKILLSHARE_PACKAGE.selected!.files : [], filesTotal: request.type === "publish" ? 2 : 0, scripts, secrets: [], warnings: [t("演示操作只更新此界面。", "Demo actions update only this surface.")] }); return;
    }
    const value = await invoke("skillshare.prepare", { sessionId: sessionId!, action: request }); if (generation === epoch.current) setReview(value.review);
  });
  const submit = () => void run(async generation => {
    if (!review) return;
    if (preview) { setAction({ id: review.id, type: review.action.type, state: "completed", message: t("演示操作已完成；没有写入本机或注册表。", "Demo completed; no local or registry writes occurred.") }); setReview(undefined); return; }
    const value = await invoke("skillshare.execute", { sessionId: sessionId!, id: review.id, digest: review.digest, allowScripts, allowSecrets }); if (generation === epoch.current) { setAction(value.action); setReview(undefined); }
  });
  const readPackage = (name: string, requestedVersion?: string, offset?: number) => void run(async generation => {
    if (preview) { setDetail(PREVIEW_SKILLSHARE_PACKAGE); setPackageName(PREVIEW_SKILLSHARE_PACKAGE.package); return; }
    const value = await invoke("skillshare.package", { sessionId: sessionId!, package: name, ...(requestedVersion ? { version: requestedVersion } : {}), ...(offset !== undefined ? { offset } : {}) }); if (generation === epoch.current) { setDetail(value); setPackageName(name); }
  });
  const find = (page = 0) => void run(async generation => { if (preview) { setSearch(PREVIEW_SKILLSHARE_SEARCH); return; } const value = await invoke("skillshare.search", { sessionId: sessionId!, query, sort, page }); if (generation === epoch.current) setSearch(value); });
  const words = (value: string) => value.split(/[\s,]+/u).filter(Boolean);
  const manage = () => {
    const request: SkillshareAction = actionType === "publish" ? { type: "publish", directory, scope: publishScope, ...(tag ? { tag } : {}) }
      : actionType === "version" ? { type: "version", directory, bump }
      : actionType === "import" ? { type: "import", file: directory }
      : actionType === "tag.set" ? { type: "tag.set", package: packageName, tag, version }
      : actionType === "tag.remove" ? { type: "tag.remove", package: packageName, tag }
      : actionType === "yank" ? { type: "yank", package: packageName, version, yanked }
      : actionType === "deprecate" ? { type: "deprecate", package: packageName, version, message: message || null }
      : actionType === "owner.add" || actionType === "owner.remove" ? { type: actionType, package: packageName, username }
      : { type: "reload" };
    prepare(request);
  };
  return <section className="skillshare-pane" aria-label="Skillshare">
    <div className="skillshare-toolbar"><h3>Skillshare</h3>{preview ? <span className="chip gray">{t("演示", "Demo")}</span> : null}<span className="small muted">{status?.registry ?? t("未连接", "Disconnected")}</span><button className="btn small outline" disabled={busy || !enabled} onClick={() => void run(async () => load())}>{t("刷新状态", "Refresh status")}</button></div>
    <p className="small muted">{t("安装与发布复用 OMP 原生注册表。远程写入必须先检查确认单；脚本不会在安装时执行。", "Uses the native OMP registry. Review every remote write before confirming; installation does not execute package scripts.")}</p>
    {!enabled ? <p className="muted">{t("连接活动 Runtime 后可使用注册表。", "Connect an active Runtime to use the registry.")}</p> : null}
    {status ? <p className="small muted">{t("账户认证", "Account authentication")}: {status.accountAuthenticated ? "✓" : "—"} · {t("发布认证", "Publishing authentication")}: {status.publishAuthenticated ? "✓" : "—"} · {t("在模型凭据中登录 Stencil；发布也可沿用 Runtime 的 SKILLS_TOKEN。", "Sign into Stencil in model credentials; publishing also honors the Runtime SKILLS_TOKEN.")}</p> : null}
    <div className="skillshare-tabs" role="tablist" aria-label={t("注册表视图", "Registry view")}>{(["browse", "installed", "manage", "tokens"] as const).map(name => <button key={name} role="tab" aria-selected={tab === name} className={`btn small ${tab === name ? "primary" : "outline"}`} onClick={() => setTab(name)}>{{ browse: t("发现与安装", "Discover / install"), installed: t("已安装", "Installed"), manage: t("发布与维护", "Publish / maintain"), tokens: t("发布令牌", "Publish tokens") }[name]}</button>)}</div>
    {tab === "browse" ? <><div className="skillshare-toolbar"><input className="input" aria-label={t("搜索 Skillshare", "Search Skillshare")} placeholder="owner:scope / keyword:review" value={query} onChange={event => setQuery(event.target.value)} /><select className="select" aria-label={t("搜索排序", "Search order")} value={sort} onChange={event => setSort(event.target.value as typeof sort)}><option value="relevance">{t("相关性", "Relevance")}</option><option value="downloads">{t("下载量", "Downloads")}</option><option value="recent">{t("最近更新", "Recent")}</option></select><button className="btn small" disabled={busy || !enabled} onClick={() => find()}>{t("搜索", "Search")}</button><button className="btn small outline" disabled={busy || !enabled} onClick={() => void run(async generation => { if (preview) { setSearch(PREVIEW_SKILLSHARE_SEARCH); return; } const home = await invoke("skillshare.home", { sessionId: sessionId! }); if (generation === epoch.current) setSearch({ hits: [...new Map([...home.trending, ...home.popular, ...home.recent].map(hit => [hit.package, hit])).values()], total: home.stats.packages, page: 0, perPage: 150 }); })}>{t("浏览热门与新发布", "Explore registry")}</button></div>
      <div className="skillshare-hits">{search?.hits.map(hit => <button className="skillshare-hit" key={hit.package} onClick={() => readPackage(hit.package, hit.version)}><strong>{hit.package} <small>{hit.version}</small></strong><span>{hit.description}</span><small>{hit.downloads} {t("周下载", "weekly downloads")}{hit.deprecated ? " · " + hit.deprecated : ""}</small></button>)}</div>
      {search && search.perPage !== 150 ? <div className="skillshare-toolbar"><span className="small muted">{search.total} · {search.page + 1}</span><button className="btn small" disabled={busy || search.page === 0} onClick={() => find(search.page - 1)}>{t("上一页", "Previous")}</button><button className="btn small" disabled={busy || (search.page + 1) * search.perPage >= search.total} onClick={() => find(search.page + 1)}>{t("下一页", "Next")}</button></div> : null}
      {!search ? <p className="muted">{t("搜索或浏览注册表以查看可安装的技能。", "Search or explore the registry for skills.")}</p> : null}
      <div className="skillshare-form"><label>{t("安装包（空格分隔，留空恢复 manifest / lock）", "Package specs (space separated; blank restores manifest / lock)")}<input className="input" placeholder="@scope/name@^1.0.0" value={specs} onChange={event => setSpecs(event.target.value)} /></label><label>{t("安装范围", "Install scope")}<select className="select" value={scope} onChange={event => setScope(event.target.value as typeof scope)}><option value="project">{t("当前项目", "Project")}</option><option value="user">{t("当前用户", "User")}</option></select></label><button className="btn small primary" disabled={busy || !enabled} onClick={() => prepare({ type: "install", specs: words(specs), scope })}>{t("检查安装请求", "Review installation")}</button></div>
    </> : null}
    {tab === "installed" ? <><div className="skillshare-toolbar"><select className="select" aria-label={t("更新范围", "Update scope")} value={scope} onChange={event => setScope(event.target.value as typeof scope)}><option value="project">{t("当前项目", "Project")}</option><option value="user">{t("当前用户", "User")}</option></select><button className="btn small" disabled={busy || !enabled} onClick={() => prepare({ type: "update", names: [], scope })}>{t("检查该范围全部更新", "Review all updates in scope")}</button><button className="btn small outline" disabled={busy || !enabled} onClick={() => prepare({ type: "reload" })}>{t("检查技能重载请求", "Review skill refresh")}</button></div><div className="skillshare-installed">{installed?.skills.map(row => <div key={row.scope + row.package}><button className="btn small" onClick={() => readPackage(row.package, row.version)}>{row.package}</button><span>{row.scope} · {row.version ?? "—"} · {row.range ?? "—"}{row.stored ? "" : t(" · 需要恢复文件", " · needs restore")}</span><button className="btn small outline" disabled={busy || !enabled} onClick={() => prepare({ type: "update", names: [row.package], scope: row.scope })}>{t("更新", "Update")}</button><button className="btn small outline" disabled={busy || !enabled} onClick={() => prepare({ type: "uninstall", names: [row.package], scope: row.scope })}>{t("卸载", "Uninstall")}</button></div>)}</div>{!installed?.skills.length ? <p className="muted">{t("此处仅列出原生 Skillshare manifest / lock 中的安装。", "Only native Skillshare manifest / lock installations appear here.")}</p> : null}{installed?.nextOffset !== undefined ? <button className="btn small" disabled={busy} onClick={() => void run(async generation => { const value = await invoke("skillshare.installed", { sessionId: sessionId!, offset: installed.nextOffset! }); if (generation === epoch.current) setInstalled(previous => ({ ...value, skills: [...(previous?.skills ?? []), ...value.skills] })); })}>{t("加载更多安装", "Load more installations")}</button> : null}</> : null}
    {tab === "manage" ? <div className="skillshare-form"><label>{t("维护动作", "Maintenance action")}<select className="select" value={actionType} onChange={event => setActionType(event.target.value as typeof actionType)}>{["publish", "version", "import", "tag.set", "tag.remove", "yank", "deprecate", "owner.add", "owner.remove", "reload"].map(value => <option key={value} value={value}>{{ publish: t("发布本地目录", "Publish directory"), version: t("修改本地版本号", "Bump local version"), import: t("导入并发布 .skill", "Import and publish .skill"), "tag.set": t("设置版本标签", "Set tag"), "tag.remove": t("移除版本标签", "Remove tag"), yank: t("撤回 / 恢复版本", "Yank / restore version"), deprecate: t("弃用 / 取消弃用", "Deprecate / clear"), "owner.add": t("添加维护者", "Add owner"), "owner.remove": t("移除维护者", "Remove owner"), reload: t("重新加载技能", "Refresh skills") }[value]}</option>)}</select></label>
      {["publish", "version", "import"].includes(actionType) ? <label>{actionType === "import" ? t("工作区内 .skill 文件", ".skill path in workspace") : t("工作区内技能目录", "Skill directory in workspace")}<input className="input" value={directory} onChange={event => setDirectory(event.target.value)} /></label> : actionType !== "reload" ? <label>{t("注册表包", "Registry package")}<input className="input" placeholder="@scope/name" value={packageName} onChange={event => setPackageName(event.target.value)} /></label> : null}
      {actionType === "publish" ? <label>{t("发布命名空间", "Publishing scope")}<input className="input" placeholder="username" value={publishScope} onChange={event => setPublishScope(event.target.value)} /></label> : null}
      {["publish", "tag.set", "tag.remove"].includes(actionType) ? <label>{t("版本标签", "Dist-tag")}<input className="input" value={tag} onChange={event => setTag(event.target.value)} /></label> : null}
      {["tag.set", "yank", "deprecate"].includes(actionType) ? <label>{t("精确版本", "Exact version")}<input className="input" value={version} onChange={event => setVersion(event.target.value)} /></label> : null}
      {actionType === "version" ? <label>{t("版本递增方式或精确版本", "Bump kind or exact version")}<input className="input" placeholder="patch / minor / major / 1.2.3" value={bump} onChange={event => setBump(event.target.value)} /></label> : null}
      {actionType === "deprecate" ? <label>{t("弃用说明（留空取消弃用）", "Deprecation message (blank clears)")}<input className="input" maxLength={500} value={message} onChange={event => setMessage(event.target.value)} /></label> : null}
      {actionType === "yank" ? <label><input type="checkbox" checked={yanked} onChange={event => setYanked(event.target.checked)} />{t("撤回该版本（取消勾选则恢复）", "Yank this version (uncheck to restore)")}</label> : null}
      {actionType.startsWith("owner.") ? <label>{t("维护者用户名", "Owner username")}<input className="input" value={username} onChange={event => setUsername(event.target.value)} /></label> : null}
      <button className="btn small primary" disabled={busy || !enabled} onClick={manage}>{t("生成维护确认单", "Prepare maintenance review")}</button>
    </div> : null}
    {tab === "tokens" ? <><div className="skillshare-toolbar"><button className="btn small outline" disabled={busy || !enabled} onClick={() => void run(async generation => { if (preview) { setTokens(PREVIEW_SKILLSHARE_TOKENS); return; } const value = await invoke("skillshare.tokens", { sessionId: sessionId! }); if (generation === epoch.current) setTokens(value); })}>{t("读取发布令牌", "List publish tokens")}</button></div><p className="small muted">{t("令牌列表只显示元数据。新令牌通过桌面私有通道仅展示一次，需手动复制；不会自动保存。", "Lists contain metadata only. New tokens are revealed once through the private desktop channel; copy manually. No automatic saving.")}</p>
      {tokens?.tokens.map(token => <div className="skillshare-token" key={token.id}><strong>{token.name}</strong><code>{token.id}</code><span>{token.packages.join(", ") || t("管理的所有包", "All managed packages")}</span><small>{t("过期", "Expires")}: {token.expiresAt ? new Date(token.expiresAt).toLocaleDateString() : t("无期限", "No expiry")}</small><button className="btn small outline" disabled={busy || !enabled} onClick={() => prepare({ type: "token.revoke", id: token.id })}>{t("检查撤销请求", "Review revocation")}</button></div>)}
      <div className="skillshare-form"><label>{t("令牌名称", "Token name")}<input className="input" value={tokenName} onChange={event => setTokenName(event.target.value)} /></label><label>{t("允许发布的包（留空为全部）", "Allowed packages (blank means all)")}<input className="input" placeholder="@scope/name" value={tokenPackages} onChange={event => setTokenPackages(event.target.value)} /></label><label>{t("有效天数（留空沿用上游默认）", "Expiry days (blank uses native default)")}<input className="input" type="number" min={1} max={3650} value={expiry} onChange={event => setExpiry(event.target.value)} /></label><button className="btn small primary" disabled={busy || !enabled || (!preview && (!status?.privateTokenChannel || !globalThis.ompStudioChrome?.revealSkillshareToken))} onClick={() => prepare({ type: "token.create", name: tokenName, packages: words(tokenPackages), ...(expiry ? { expiresInDays: Number(expiry) } : {}) })}>{t("检查新建令牌请求", "Review token creation")}</button></div>
    </> : null}
    {detail ? <section className="skillshare-detail"><div className="skillshare-toolbar"><h4>{detail.package}</h4><button className="btn small" onClick={() => setDetail(undefined)}>{t("关闭详情", "Close details")}</button><button className="btn small outline" onClick={() => { setSpecs(detail.package + (detail.selected ? "@" + detail.selected.version.version : "")); setTab("browse"); }}>{t("放入安装表单", "Use in install form")}</button></div><p>{detail.description}</p><p className="small muted">{t("维护者", "Owners")}: {detail.owners.join(", ")} · {Object.entries(detail.tags).map(([tag, version]) => tag + " → " + version).join(" · ")}</p><div className="skillshare-versions">{detail.versions.map(row => <button className="btn small outline" key={row.version} disabled={busy} onClick={() => { setVersion(row.version); readPackage(detail.package, row.version); }}>{row.version}{row.yanked ? " · yanked" : ""}{row.deprecated ? " · deprecated" : ""}{row.hasScripts ? " · scripts" : ""}</button>)}{detail.nextOffset !== undefined ? <button className="btn small" disabled={busy} onClick={() => readPackage(detail.package, undefined, detail.nextOffset)}>{t("更多版本", "More versions")}</button> : null}</div>{detail.selected ? <><p className="small muted">{detail.selected.publisher} · {detail.selected.provenance}</p><code className="skillshare-integrity">{detail.selected.version.integrity}</code><div className="skillshare-file-list">{detail.selected.files.map(file => <div key={file.path}><code>{file.path}</code><span>{file.size} B{file.executable ? " · executable" : ""}</span></div>)}</div></> : null}</section> : null}
    {status?.actions.length ? <div className="skillshare-toolbar"><span className="small muted">{t("当前会话的操作记录", "Actions in this session")}</span>{status.actions.map(item => <span key={item.id}><button className="btn small" disabled={busy} onClick={() => setAction(item)}>{item.type} · {item.state}</button><button className="btn small" aria-label={t("丢弃操作记录", "Discard action record")} disabled={busy || item.state === "running"} onClick={() => void run(async () => { if (!preview) await invoke("skillshare.discard", { sessionId: sessionId!, id: item.id }); await load(); })}>×</button></span>)}</div> : null}
    {action ? <section className="skillshare-action" role="status"><strong>{action.type} · {action.state}</strong><p>{action.message}</p>{action.link ? <button className="btn small outline" disabled={!globalThis.ompStudioChrome?.openUrl} onClick={() => { if (!preview) void globalThis.ompStudioChrome?.openUrl({ url: action.link! }); }}>{t("在浏览器查看", "View in browser")}</button> : null}{action.secretId ? <button className="btn small primary" disabled={busy || !globalThis.ompStudioChrome?.revealSkillshareToken} onClick={() => void run(async generation => { const value = await globalThis.ompStudioChrome!.revealSkillshareToken!({ sessionId: sessionId!, secretId: action.secretId! }); if (!value.ok || !value.token) throw new Error(value.message ?? "Secret unavailable"); if (generation === epoch.current && !document.hidden) { setSecret({ token: value.token, name: value.name ?? "" }); setAction(previous => { if (!previous) return previous; const { secretId: _, ...rest } = previous; return rest; }); } })}>{t("一次性显示新令牌", "Reveal new token once")}</button> : null}</section> : null}
    {secret ? <section className="skillshare-secret"><strong>{secret.name}</strong><p>{t("离开页面或隐藏窗口会清除此处的明文。请现在手动复制；无法再次获取时应撤销该令牌。", "Leaving or hiding clears this plaintext. Copy it now; revoke the token if it was not received.")}</p><input className="input mono" readOnly aria-label={t("新建令牌明文", "New token secret")} value={secret.token} /><button className="btn small" onClick={() => void navigator.clipboard.writeText(secret.token).catch(cause => setError(hostErrorMessage(cause, "Copy failed")))}>{t("复制令牌", "Copy token")}</button><button className="btn small" onClick={() => setSecret(undefined)}>{t("清除明文", "Clear plaintext")}</button></section> : null}
    {review ? <section className="skillshare-review" aria-label={t("Skillshare 确认单", "Skillshare review")}><h4>{review.action.type} · {review.remoteWrite ? t("远程写入", "Remote write") : t("本地变更", "Local change")}</h4><p>{review.registry} · {t("到期", "Expires")}: {new Date(review.expiresAt).toLocaleTimeString()}</p><pre>{JSON.stringify(review.action, null, 2)}</pre>{review.changes.map((change, index) => <p key={index}>{change.package} · {change.from ?? "—"} → {change.to ?? t("移除 / 维护", "Remove / maintain")} {change.range ?? ""}<code className="skillshare-integrity">{change.integrity}</code></p>)}{review.sourceDigest ? <code className="skillshare-integrity">SHA256 {review.sourceDigest}</code> : null}<div className="skillshare-file-list">{review.files.map(file => <div key={file.path}><code>{file.path}</code><span>{file.size} B</span></div>)}</div>{review.warnings.map((warning, index) => <p className="small" key={index}>{warning}</p>)}{review.scripts.length ? <><pre>{review.scripts.join("\n")}</pre><label><input type="checkbox" checked={allowScripts} onChange={event => setAllowScripts(event.target.checked)} />{t("已检查并接受这些包含脚本的文件", "I reviewed and accept these script-bearing files")}</label></> : null}{review.secrets.length ? <><pre>{review.secrets.map(row => `${row.path}:${row.line} · ${row.kind}`).join("\n")}</pre><label><input type="checkbox" checked={allowSecrets} onChange={event => setAllowSecrets(event.target.checked)} />{t("我已检查疑似敏感信息，并明确允许发布这些内容", "I inspected the suspected secrets and explicitly allow publishing them")}</label></> : null}<div className="skillshare-toolbar"><button ref={confirm} className="btn small primary" disabled={busy || !enabled || (!!review.scripts.length && !allowScripts) || (!!review.secrets.length && !allowSecrets)} onClick={submit}>{t("确认执行此请求", "Confirm this request")}</button><button className="btn small outline" disabled={busy} onClick={() => void run(async () => { if (!preview) await invoke("skillshare.discard", { sessionId: sessionId!, id: review.id }); setReview(undefined); })}>{t("取消确认单", "Discard review")}</button></div></section> : null}
    {busy ? <p role="status" className="small muted">{t("正在读取 / 准备…", "Reading / preparing…")}</p> : null}{error ? <p role="alert" className="skillshare-error">{error}</p> : null}
  </section>;
}
